#lang racket/base
(require "../private/tools/nest.rkt" "test-utils.rkt")
(define (two-functions)
(test-case "nesting two functions"
  (check-exn exn:fail:contract? (λ () ((∘ u n) 0)))
  (check-equal? ((∘ u n))	(u (n)))
  (check-exn exn:fail:contract? (λ () ((∘ u u))))
  (check-exn exn:fail:contract? (λ () ((∘ u u) 0 1)))
  (check-equal? ((∘ u u) 1)	(u (u 1)))
  (check-exn exn:fail:contract? (λ () ((∘ u b) 0)))
  (check-exn exn:fail:contract? (λ () ((∘ u b) 0 1 2)))
  (check-equal? ((∘ u b) 1 2)	(u (b 1 2)))
  (check-exn exn:fail:contract? (λ () ((∘ u t) 0 1)))
  (check-exn exn:fail:contract? (λ () ((∘ u t) 0 1 2 3)))
  (check-equal? ((∘ u t) 1 2 3)	(u (t 1 2 3)))
  (check-equal? ((∘ u n*))	(u (n*)))
  (check-equal? ((∘ u n*) 1)	(u (n* 1)))
  (check-exn exn:fail:contract? (λ () ((∘ u u*))))
  (check-equal? ((∘ u u*) 1)	(u (u* 1)))
  (check-exn exn:fail:contract? (λ () ((∘ u u*))))
  (check-equal? ((∘ u u*) 1 2)	(u (u* 1 2)))
  (check-exn exn:fail:contract? (λ () ((∘ u b*) 0)))
  (check-equal? ((∘ u b*) 1 2)	(u (b* 1 2)))
  (check-exn exn:fail:contract? (λ () ((∘ u b*) 0)))
  (check-equal? ((∘ u b*) 1 2 3)	(u (b* 1 2 3)))
  (check-exn exn:fail:contract? (λ () ((∘ u v))))
  (check-exn exn:fail:contract? (λ () ((∘ u v) 0 1 2 3 4)))
  (check-equal? ((∘ u v) 1)	(u (v 1)))
  (check-exn exn:fail:contract? (λ () ((∘ u v))))
  (check-exn exn:fail:contract? (λ () ((∘ u v) 0 1 2 3 4)))
  (check-equal? ((∘ u v) 1 2)	(u (v 1 2)))
  (check-exn exn:fail:contract? (λ () ((∘ u v))))
  (check-exn exn:fail:contract? (λ () ((∘ u v) 0 1 2 3 4)))
  (check-equal? ((∘ u v) 1 2 3 4)	(u (v 1 2 3 4)))
  (check-exn exn:fail:contract? (λ () ((∘ u v*))))
  (check-equal? ((∘ u v*) 1)	(u (v* 1)))
  (check-exn exn:fail:contract? (λ () ((∘ u v*))))
  (check-equal? ((∘ u v*) 1 2)	(u (v* 1 2)))
  (check-exn exn:fail:contract? (λ () ((∘ u v*))))
  (check-equal? ((∘ u v*) 1 2 3)	(u (v* 1 2 3)))
  (check-exn exn:fail:contract? (λ () ((∘ u v*))))
  (check-equal? ((∘ u v*) 1 2 3 4)	(u (v* 1 2 3 4)))
  (check-exn exn:fail:contract? (λ () ((∘ u o))))
  (check-exn exn:fail:contract? (λ () ((∘ u o) 0 1 2)))
  (check-equal? ((∘ u o) 1)	(u (o 1 88)))
  (check-exn exn:fail:contract? (λ () ((∘ u o))))
  (check-exn exn:fail:contract? (λ () ((∘ u o) 0 1 2)))
  (check-equal? ((∘ u o) 1 2)	(u (o 1 2)))
  (check-exn exn:fail:contract? (λ () ((∘ b n))))
  (check-exn exn:fail:contract? (λ () ((∘ b n) 0 1)))
  (check-equal? ((∘ b n) 1)	(b (n) 1))
  (check-exn exn:fail:contract? (λ () ((∘ b u) 0)))
  (check-exn exn:fail:contract? (λ () ((∘ b u) 0 1 2)))
  (check-equal? ((∘ b u) 1 2)	(b (u 1) 2))
  (check-exn exn:fail:contract? (λ () ((∘ b b) 0 1)))
  (check-exn exn:fail:contract? (λ () ((∘ b b) 0 1 2 3)))
  (check-equal? ((∘ b b) 1 2 3)	(b (b 1 2) 3))
  (check-exn exn:fail:contract? (λ () ((∘ b t) 0 1 2)))
  (check-exn exn:fail:contract? (λ () ((∘ b t) 0 1 2 3 4)))
  (check-equal? ((∘ b t) 1 2 3 4)	(b (t 1 2 3) 4))
  (check-exn exn:fail:contract? (λ () ((∘ b n*) 0)))
  (check-exn exn:fail:contract? (λ () ((∘ b n*) 0 1 2)))
  (check-equal? ((∘ b n*) 1 2)	(b (n* 1) 2))
  (check-exn exn:fail:contract? (λ () ((∘ b u*) 0)))
  (check-exn exn:fail:contract? (λ () ((∘ b u*) 0 1 2)))
  (check-equal? ((∘ b u*) 1 2)	(b (u* 1) 2))
  (check-exn exn:fail:contract? (λ () ((∘ b b*) 0 1)))
  (check-exn exn:fail:contract? (λ () ((∘ b b*) 0 1 2 3)))
  (check-equal? ((∘ b b*) 1 2 3)	(b (b* 1 2) 3))
  (check-exn exn:fail:contract? (λ () ((∘ b v) 0)))
  (check-exn exn:fail:contract? (λ () ((∘ b v) 0 1 2)))
  (check-equal? ((∘ b v) 1 2)	(b (v 1) 2))
  (check-exn exn:fail:contract? (λ () ((∘ b v*) 0)))
  (check-exn exn:fail:contract? (λ () ((∘ b v*) 0 1 2)))
  (check-equal? ((∘ b v*) 1 2)	(b (v* 1) 2))
  (check-exn exn:fail:contract? (λ () ((∘ b o) 0)))
  (check-exn exn:fail:contract? (λ () ((∘ b o) 0 1 2)))
  (check-equal? ((∘ b o) 1 2)	(b (o 1 88) 2))
  (check-exn exn:fail:contract? (λ () ((∘ t n) 0)))
  (check-exn exn:fail:contract? (λ () ((∘ t n) 0 1 2)))
  (check-equal? ((∘ t n) 1 2)	(t (n) 1 2))
  (check-exn exn:fail:contract? (λ () ((∘ t u) 0 1)))
  (check-exn exn:fail:contract? (λ () ((∘ t u) 0 1 2 3)))
  (check-equal? ((∘ t u) 1 2 3)	(t (u 1) 2 3))
  (check-exn exn:fail:contract? (λ () ((∘ t b) 0 1 2)))
  (check-exn exn:fail:contract? (λ () ((∘ t b) 0 1 2 3 4)))
  (check-equal? ((∘ t b) 1 2 3 4)	(t (b 1 2) 3 4))
  (check-exn exn:fail:contract? (λ () ((∘ t t) 0 1 2 3)))
  (check-exn exn:fail:contract? (λ () ((∘ t t) 0 1 2 3 4 5)))
  (check-equal? ((∘ t t) 1 2 3 4 5)	(t (t 1 2 3) 4 5))
  (check-exn exn:fail:contract? (λ () ((∘ t n*) 0 1)))
  (check-exn exn:fail:contract? (λ () ((∘ t n*) 0 1 2 3)))
  (check-equal? ((∘ t n*) 1 2 3)	(t (n* 1) 2 3))
  (check-exn exn:fail:contract? (λ () ((∘ t u*) 0 1)))
  (check-exn exn:fail:contract? (λ () ((∘ t u*) 0 1 2 3)))
  (check-equal? ((∘ t u*) 1 2 3)	(t (u* 1) 2 3))
  (check-exn exn:fail:contract? (λ () ((∘ t b*) 0 1 2)))
  (check-exn exn:fail:contract? (λ () ((∘ t b*) 0 1 2 3 4)))
  (check-equal? ((∘ t b*) 1 2 3 4)	(t (b* 1 2) 3 4))
  (check-exn exn:fail:contract? (λ () ((∘ t v) 0 1)))
  (check-exn exn:fail:contract? (λ () ((∘ t v) 0 1 2 3)))
  (check-equal? ((∘ t v) 1 2 3)	(t (v 1) 2 3))
  (check-exn exn:fail:contract? (λ () ((∘ t v*) 0 1)))
  (check-exn exn:fail:contract? (λ () ((∘ t v*) 0 1 2 3)))
  (check-equal? ((∘ t v*) 1 2 3)	(t (v* 1) 2 3))
  (check-exn exn:fail:contract? (λ () ((∘ t o) 0 1)))
  (check-exn exn:fail:contract? (λ () ((∘ t o) 0 1 2 3)))
  (check-equal? ((∘ t o) 1 2 3)	(t (o 1 88) 2 3))
  (check-equal? ((∘ u* n))	(u* (n)))
  (check-equal? ((∘ u* n) 1)	(u* (n) 1))
  (check-exn exn:fail:contract? (λ () ((∘ u* u))))
  (check-equal? ((∘ u* u) 1)	(u* (u 1)))
  (check-exn exn:fail:contract? (λ () ((∘ u* u))))
  (check-equal? ((∘ u* u) 1 2)	(u* (u 1) 2))
  (check-exn exn:fail:contract? (λ () ((∘ u* b) 0)))
  (check-equal? ((∘ u* b) 1 2)	(u* (b 1 2)))
  (check-exn exn:fail:contract? (λ () ((∘ u* b) 0)))
  (check-equal? ((∘ u* b) 1 2 3)	(u* (b 1 2) 3))
  (check-exn exn:fail:contract? (λ () ((∘ u* t) 0 1)))
  (check-equal? ((∘ u* t) 1 2 3)	(u* (t 1 2 3)))
  (check-exn exn:fail:contract? (λ () ((∘ u* t) 0 1)))
  (check-equal? ((∘ u* t) 1 2 3 4)	(u* (t 1 2 3) 4))
  (check-exn exn:fail:contract? (λ () ((∘ u* n*))))
  (check-equal? ((∘ u* n*) 1)	(u* (n* 1)))
  (check-exn exn:fail:contract? (λ () ((∘ u* n*))))
  (check-equal? ((∘ u* n*) 1 2)	(u* (n* 1) 2))
  (check-exn exn:fail:contract? (λ () ((∘ u* u*))))
  (check-equal? ((∘ u* u*) 1)	(u* (u* 1)))
  (check-exn exn:fail:contract? (λ () ((∘ u* u*))))
  (check-equal? ((∘ u* u*) 1 2)	(u* (u* 1) 2))
  (check-exn exn:fail:contract? (λ () ((∘ u* b*) 0)))
  (check-equal? ((∘ u* b*) 1 2)	(u* (b* 1 2)))
  (check-exn exn:fail:contract? (λ () ((∘ u* b*) 0)))
  (check-equal? ((∘ u* b*) 1 2 3)	(u* (b* 1 2) 3))
  (check-exn exn:fail:contract? (λ () ((∘ u* v))))
  (check-equal? ((∘ u* v) 1)	(u* (v 1)))
  (check-exn exn:fail:contract? (λ () ((∘ u* v))))
  (check-equal? ((∘ u* v) 1 2)	(u* (v 1) 2))
  (check-exn exn:fail:contract? (λ () ((∘ u* v*))))
  (check-equal? ((∘ u* v*) 1)	(u* (v* 1)))
  (check-exn exn:fail:contract? (λ () ((∘ u* v*))))
  (check-equal? ((∘ u* v*) 1 2)	(u* (v* 1) 2))
  (check-exn exn:fail:contract? (λ () ((∘ u* o))))
  (check-equal? ((∘ u* o) 1)	(u* (o 1 88)))
  (check-exn exn:fail:contract? (λ () ((∘ u* o))))
  (check-equal? ((∘ u* o) 1 2)	(u* (o 1 88) 2))
  (check-exn exn:fail:contract? (λ () ((∘ b* n))))
  (check-equal? ((∘ b* n) 1)	(b* (n) 1))
  (check-exn exn:fail:contract? (λ () ((∘ b* n))))
  (check-equal? ((∘ b* n) 1 2)	(b* (n) 1 2))
  (check-exn exn:fail:contract? (λ () ((∘ b* u) 0)))
  (check-equal? ((∘ b* u) 1 2)	(b* (u 1) 2))
  (check-exn exn:fail:contract? (λ () ((∘ b* u) 0)))
  (check-equal? ((∘ b* u) 1 2 3)	(b* (u 1) 2 3))
  (check-exn exn:fail:contract? (λ () ((∘ b* b) 0 1)))
  (check-equal? ((∘ b* b) 1 2 3)	(b* (b 1 2) 3))
  (check-exn exn:fail:contract? (λ () ((∘ b* b) 0 1)))
  (check-equal? ((∘ b* b) 1 2 3 4)	(b* (b 1 2) 3 4))
  (check-exn exn:fail:contract? (λ () ((∘ b* t) 0 1 2)))
  (check-equal? ((∘ b* t) 1 2 3 4)	(b* (t 1 2 3) 4))
  (check-exn exn:fail:contract? (λ () ((∘ b* t) 0 1 2)))
  (check-equal? ((∘ b* t) 1 2 3 4 5)	(b* (t 1 2 3) 4 5))
  (check-exn exn:fail:contract? (λ () ((∘ b* n*) 0)))
  (check-equal? ((∘ b* n*) 1 2)	(b* (n* 1) 2))
  (check-exn exn:fail:contract? (λ () ((∘ b* n*) 0)))
  (check-equal? ((∘ b* n*) 1 2 3)	(b* (n* 1) 2 3))
  (check-exn exn:fail:contract? (λ () ((∘ b* u*) 0)))
  (check-equal? ((∘ b* u*) 1 2)	(b* (u* 1) 2))
  (check-exn exn:fail:contract? (λ () ((∘ b* u*) 0)))
  (check-equal? ((∘ b* u*) 1 2 3)	(b* (u* 1) 2 3))
  (check-exn exn:fail:contract? (λ () ((∘ b* b*) 0 1)))
  (check-equal? ((∘ b* b*) 1 2 3)	(b* (b* 1 2) 3))
  (check-exn exn:fail:contract? (λ () ((∘ b* b*) 0 1)))
  (check-equal? ((∘ b* b*) 1 2 3 4)	(b* (b* 1 2) 3 4))
  (check-exn exn:fail:contract? (λ () ((∘ b* v) 0)))
  (check-equal? ((∘ b* v) 1 2)	(b* (v 1) 2))
  (check-exn exn:fail:contract? (λ () ((∘ b* v) 0)))
  (check-equal? ((∘ b* v) 1 2 3)	(b* (v 1) 2 3))
  (check-exn exn:fail:contract? (λ () ((∘ b* v*) 0)))
  (check-equal? ((∘ b* v*) 1 2)	(b* (v* 1) 2))
  (check-exn exn:fail:contract? (λ () ((∘ b* v*) 0)))
  (check-equal? ((∘ b* v*) 1 2 3)	(b* (v* 1) 2 3))
  (check-exn exn:fail:contract? (λ () ((∘ b* o) 0)))
  (check-equal? ((∘ b* o) 1 2)	(b* (o 1 88) 2))
  (check-exn exn:fail:contract? (λ () ((∘ b* o) 0)))
  (check-equal? ((∘ b* o) 1 2 3)	(b* (o 1 88) 2 3))
  (check-exn exn:fail:contract? (λ () ((∘ v n) 0 1 2 3)))
  (check-equal? ((∘ v n))	(v (n)))
  (check-exn exn:fail:contract? (λ () ((∘ v n) 0 1 2 3)))
  (check-equal? ((∘ v n) 1)	(v (n) 1))
  (check-exn exn:fail:contract? (λ () ((∘ v n) 0 1 2 3)))
  (check-equal? ((∘ v n) 1 2 3)	(v (n) 1 2 3))
  (check-exn exn:fail:contract? (λ () ((∘ v u))))
  (check-exn exn:fail:contract? (λ () ((∘ v u) 0 1 2 3 4)))
  (check-equal? ((∘ v u) 1)	(v (u 1)))
  (check-exn exn:fail:contract? (λ () ((∘ v u))))
  (check-exn exn:fail:contract? (λ () ((∘ v u) 0 1 2 3 4)))
  (check-equal? ((∘ v u) 1 2)	(v (u 1) 2))
  (check-exn exn:fail:contract? (λ () ((∘ v u))))
  (check-exn exn:fail:contract? (λ () ((∘ v u) 0 1 2 3 4)))
  (check-equal? ((∘ v u) 1 2 3 4)	(v (u 1) 2 3 4))
  (check-exn exn:fail:contract? (λ () ((∘ v b) 0)))
  (check-exn exn:fail:contract? (λ () ((∘ v b) 0 1 2 3 4 5)))
  (check-equal? ((∘ v b) 1 2)	(v (b 1 2)))
  (check-exn exn:fail:contract? (λ () ((∘ v b) 0)))
  (check-exn exn:fail:contract? (λ () ((∘ v b) 0 1 2 3 4 5)))
  (check-equal? ((∘ v b) 1 2 3)	(v (b 1 2) 3))
  (check-exn exn:fail:contract? (λ () ((∘ v b) 0)))
  (check-exn exn:fail:contract? (λ () ((∘ v b) 0 1 2 3 4 5)))
  (check-equal? ((∘ v b) 1 2 3 4 5)	(v (b 1 2) 3 4 5))
  (check-exn exn:fail:contract? (λ () ((∘ v t) 0 1)))
  (check-exn exn:fail:contract? (λ () ((∘ v t) 0 1 2 3 4 5 6)))
  (check-equal? ((∘ v t) 1 2 3)	(v (t 1 2 3)))
  (check-exn exn:fail:contract? (λ () ((∘ v t) 0 1)))
  (check-exn exn:fail:contract? (λ () ((∘ v t) 0 1 2 3 4 5 6)))
  (check-equal? ((∘ v t) 1 2 3 4)	(v (t 1 2 3) 4))
  (check-exn exn:fail:contract? (λ () ((∘ v t) 0 1)))
  (check-exn exn:fail:contract? (λ () ((∘ v t) 0 1 2 3 4 5 6)))
  (check-equal? ((∘ v t) 1 2 3 4 5 6)	(v (t 1 2 3) 4 5 6))
  (check-exn exn:fail:contract? (λ () ((∘ v n*))))
  (check-exn exn:fail:contract? (λ () ((∘ v n*) 0 1 2 3 4)))
  (check-equal? ((∘ v n*) 1)	(v (n* 1)))
  (check-exn exn:fail:contract? (λ () ((∘ v n*))))
  (check-exn exn:fail:contract? (λ () ((∘ v n*) 0 1 2 3 4)))
  (check-equal? ((∘ v n*) 1 2)	(v (n* 1) 2))
  (check-exn exn:fail:contract? (λ () ((∘ v n*))))
  (check-exn exn:fail:contract? (λ () ((∘ v n*) 0 1 2 3 4)))
  (check-equal? ((∘ v n*) 1 2 3 4)	(v (n* 1) 2 3 4))
  (check-exn exn:fail:contract? (λ () ((∘ v u*))))
  (check-exn exn:fail:contract? (λ () ((∘ v u*) 0 1 2 3 4)))
  (check-equal? ((∘ v u*) 1)	(v (u* 1)))
  (check-exn exn:fail:contract? (λ () ((∘ v u*))))
  (check-exn exn:fail:contract? (λ () ((∘ v u*) 0 1 2 3 4)))
  (check-equal? ((∘ v u*) 1 2)	(v (u* 1) 2))
  (check-exn exn:fail:contract? (λ () ((∘ v u*))))
  (check-exn exn:fail:contract? (λ () ((∘ v u*) 0 1 2 3 4)))
  (check-equal? ((∘ v u*) 1 2 3 4)	(v (u* 1) 2 3 4))
  (check-exn exn:fail:contract? (λ () ((∘ v b*) 0)))
  (check-exn exn:fail:contract? (λ () ((∘ v b*) 0 1 2 3 4 5)))
  (check-equal? ((∘ v b*) 1 2)	(v (b* 1 2)))
  (check-exn exn:fail:contract? (λ () ((∘ v b*) 0)))
  (check-exn exn:fail:contract? (λ () ((∘ v b*) 0 1 2 3 4 5)))
  (check-equal? ((∘ v b*) 1 2 3)	(v (b* 1 2) 3))
  (check-exn exn:fail:contract? (λ () ((∘ v b*) 0)))
  (check-exn exn:fail:contract? (λ () ((∘ v b*) 0 1 2 3 4 5)))
  (check-equal? ((∘ v b*) 1 2 3 4 5)	(v (b* 1 2) 3 4 5))
  (check-exn exn:fail:contract? (λ () ((∘ v v))))
  (check-exn exn:fail:contract? (λ () ((∘ v v) 0 1 2 3 4)))
  (check-equal? ((∘ v v) 1)	(v (v 1)))
  (check-exn exn:fail:contract? (λ () ((∘ v v))))
  (check-exn exn:fail:contract? (λ () ((∘ v v) 0 1 2 3 4)))
  (check-equal? ((∘ v v) 1 2)	(v (v 1) 2))
  (check-exn exn:fail:contract? (λ () ((∘ v v))))
  (check-exn exn:fail:contract? (λ () ((∘ v v) 0 1 2 3 4)))
  (check-equal? ((∘ v v) 1 2 3 4)	(v (v 1) 2 3 4))
  (check-exn exn:fail:contract? (λ () ((∘ v v*))))
  (check-exn exn:fail:contract? (λ () ((∘ v v*) 0 1 2 3 4)))
  (check-equal? ((∘ v v*) 1)	(v (v* 1)))
  (check-exn exn:fail:contract? (λ () ((∘ v v*))))
  (check-exn exn:fail:contract? (λ () ((∘ v v*) 0 1 2 3 4)))
  (check-equal? ((∘ v v*) 1 2)	(v (v* 1) 2))
  (check-exn exn:fail:contract? (λ () ((∘ v v*))))
  (check-exn exn:fail:contract? (λ () ((∘ v v*) 0 1 2 3 4)))
  (check-equal? ((∘ v v*) 1 2 3 4)	(v (v* 1) 2 3 4))
  (check-exn exn:fail:contract? (λ () ((∘ v o))))
  (check-exn exn:fail:contract? (λ () ((∘ v o) 0 1 2 3 4)))
  (check-equal? ((∘ v o) 1)	(v (o 1 88)))
  (check-exn exn:fail:contract? (λ () ((∘ v o))))
  (check-exn exn:fail:contract? (λ () ((∘ v o) 0 1 2 3 4)))
  (check-equal? ((∘ v o) 1 2)	(v (o 1 88) 2))
  (check-exn exn:fail:contract? (λ () ((∘ v o))))
  (check-exn exn:fail:contract? (λ () ((∘ v o) 0 1 2 3 4)))
  (check-equal? ((∘ v o) 1 2 3 4)	(v (o 1 88) 2 3 4))
  (check-equal? ((∘ v* n))	(v* (n)))
  (check-equal? ((∘ v* n) 1)	(v* (n) 1))
  (check-equal? ((∘ v* n) 1 2)	(v* (n) 1 2))
  (check-equal? ((∘ v* n) 1 2 3)	(v* (n) 1 2 3))
  (check-exn exn:fail:contract? (λ () ((∘ v* u))))
  (check-equal? ((∘ v* u) 1)	(v* (u 1)))
  (check-exn exn:fail:contract? (λ () ((∘ v* u))))
  (check-equal? ((∘ v* u) 1 2)	(v* (u 1) 2))
  (check-exn exn:fail:contract? (λ () ((∘ v* u))))
  (check-equal? ((∘ v* u) 1 2 3)	(v* (u 1) 2 3))
  (check-exn exn:fail:contract? (λ () ((∘ v* u))))
  (check-equal? ((∘ v* u) 1 2 3 4)	(v* (u 1) 2 3 4))
  (check-exn exn:fail:contract? (λ () ((∘ v* b) 0)))
  (check-equal? ((∘ v* b) 1 2)	(v* (b 1 2)))
  (check-exn exn:fail:contract? (λ () ((∘ v* b) 0)))
  (check-equal? ((∘ v* b) 1 2 3)	(v* (b 1 2) 3))
  (check-exn exn:fail:contract? (λ () ((∘ v* b) 0)))
  (check-equal? ((∘ v* b) 1 2 3 4)	(v* (b 1 2) 3 4))
  (check-exn exn:fail:contract? (λ () ((∘ v* b) 0)))
  (check-equal? ((∘ v* b) 1 2 3 4 5)	(v* (b 1 2) 3 4 5))
  (check-exn exn:fail:contract? (λ () ((∘ v* t) 0 1)))
  (check-equal? ((∘ v* t) 1 2 3)	(v* (t 1 2 3)))
  (check-exn exn:fail:contract? (λ () ((∘ v* t) 0 1)))
  (check-equal? ((∘ v* t) 1 2 3 4)	(v* (t 1 2 3) 4))
  (check-exn exn:fail:contract? (λ () ((∘ v* t) 0 1)))
  (check-equal? ((∘ v* t) 1 2 3 4 5)	(v* (t 1 2 3) 4 5))
  (check-exn exn:fail:contract? (λ () ((∘ v* t) 0 1)))
  (check-equal? ((∘ v* t) 1 2 3 4 5 6)	(v* (t 1 2 3) 4 5 6))
  (check-exn exn:fail:contract? (λ () ((∘ v* n*))))
  (check-equal? ((∘ v* n*) 1)	(v* (n* 1)))
  (check-exn exn:fail:contract? (λ () ((∘ v* n*))))
  (check-equal? ((∘ v* n*) 1 2)	(v* (n* 1) 2))
  (check-exn exn:fail:contract? (λ () ((∘ v* n*))))
  (check-equal? ((∘ v* n*) 1 2 3)	(v* (n* 1) 2 3))
  (check-exn exn:fail:contract? (λ () ((∘ v* n*))))
  (check-equal? ((∘ v* n*) 1 2 3 4)	(v* (n* 1) 2 3 4))
  (check-exn exn:fail:contract? (λ () ((∘ v* u*))))
  (check-equal? ((∘ v* u*) 1)	(v* (u* 1)))
  (check-exn exn:fail:contract? (λ () ((∘ v* u*))))
  (check-equal? ((∘ v* u*) 1 2)	(v* (u* 1) 2))
  (check-exn exn:fail:contract? (λ () ((∘ v* u*))))
  (check-equal? ((∘ v* u*) 1 2 3)	(v* (u* 1) 2 3))
  (check-exn exn:fail:contract? (λ () ((∘ v* u*))))
  (check-equal? ((∘ v* u*) 1 2 3 4)	(v* (u* 1) 2 3 4))
  (check-exn exn:fail:contract? (λ () ((∘ v* b*) 0)))
  (check-equal? ((∘ v* b*) 1 2)	(v* (b* 1 2)))
  (check-exn exn:fail:contract? (λ () ((∘ v* b*) 0)))
  (check-equal? ((∘ v* b*) 1 2 3)	(v* (b* 1 2) 3))
  (check-exn exn:fail:contract? (λ () ((∘ v* b*) 0)))
  (check-equal? ((∘ v* b*) 1 2 3 4)	(v* (b* 1 2) 3 4))
  (check-exn exn:fail:contract? (λ () ((∘ v* b*) 0)))
  (check-equal? ((∘ v* b*) 1 2 3 4 5)	(v* (b* 1 2) 3 4 5))
  (check-exn exn:fail:contract? (λ () ((∘ v* v))))
  (check-equal? ((∘ v* v) 1)	(v* (v 1)))
  (check-exn exn:fail:contract? (λ () ((∘ v* v))))
  (check-equal? ((∘ v* v) 1 2)	(v* (v 1) 2))
  (check-exn exn:fail:contract? (λ () ((∘ v* v))))
  (check-equal? ((∘ v* v) 1 2 3)	(v* (v 1) 2 3))
  (check-exn exn:fail:contract? (λ () ((∘ v* v))))
  (check-equal? ((∘ v* v) 1 2 3 4)	(v* (v 1) 2 3 4))
  (check-exn exn:fail:contract? (λ () ((∘ v* v*))))
  (check-equal? ((∘ v* v*) 1)	(v* (v* 1)))
  (check-exn exn:fail:contract? (λ () ((∘ v* v*))))
  (check-equal? ((∘ v* v*) 1 2)	(v* (v* 1) 2))
  (check-exn exn:fail:contract? (λ () ((∘ v* v*))))
  (check-equal? ((∘ v* v*) 1 2 3)	(v* (v* 1) 2 3))
  (check-exn exn:fail:contract? (λ () ((∘ v* v*))))
  (check-equal? ((∘ v* v*) 1 2 3 4)	(v* (v* 1) 2 3 4))
  (check-exn exn:fail:contract? (λ () ((∘ v* o))))
  (check-equal? ((∘ v* o) 1)	(v* (o 1 88)))
  (check-exn exn:fail:contract? (λ () ((∘ v* o))))
  (check-equal? ((∘ v* o) 1 2)	(v* (o 1 88) 2))
  (check-exn exn:fail:contract? (λ () ((∘ v* o))))
  (check-equal? ((∘ v* o) 1 2 3)	(v* (o 1 88) 2 3))
  (check-exn exn:fail:contract? (λ () ((∘ v* o))))
  (check-equal? ((∘ v* o) 1 2 3 4)	(v* (o 1 88) 2 3 4))
  (check-exn exn:fail:contract? (λ () ((∘ o n) 0 1)))
  (check-equal? ((∘ o n))	(o (n) 88))
  (check-exn exn:fail:contract? (λ () ((∘ o n) 0 1)))
  (check-equal? ((∘ o n) 1)	(o (n) 1))
  (check-exn exn:fail:contract? (λ () ((∘ o u))))
  (check-exn exn:fail:contract? (λ () ((∘ o u) 0 1 2)))
  (check-equal? ((∘ o u) 1)	(o (u 1) 88))
  (check-exn exn:fail:contract? (λ () ((∘ o u))))
  (check-exn exn:fail:contract? (λ () ((∘ o u) 0 1 2)))
  (check-equal? ((∘ o u) 1 2)	(o (u 1) 2))
  (check-exn exn:fail:contract? (λ () ((∘ o b) 0)))
  (check-exn exn:fail:contract? (λ () ((∘ o b) 0 1 2 3)))
  (check-equal? ((∘ o b) 1 2)	(o (b 1 2) 88))
  (check-exn exn:fail:contract? (λ () ((∘ o b) 0)))
  (check-exn exn:fail:contract? (λ () ((∘ o b) 0 1 2 3)))
  (check-equal? ((∘ o b) 1 2 3)	(o (b 1 2) 3))
  (check-exn exn:fail:contract? (λ () ((∘ o t) 0 1)))
  (check-exn exn:fail:contract? (λ () ((∘ o t) 0 1 2 3 4)))
  (check-equal? ((∘ o t) 1 2 3)	(o (t 1 2 3) 88))
  (check-exn exn:fail:contract? (λ () ((∘ o t) 0 1)))
  (check-exn exn:fail:contract? (λ () ((∘ o t) 0 1 2 3 4)))
  (check-equal? ((∘ o t) 1 2 3 4)	(o (t 1 2 3) 4))
  (check-exn exn:fail:contract? (λ () ((∘ o n*))))
  (check-exn exn:fail:contract? (λ () ((∘ o n*) 0 1 2)))
  (check-equal? ((∘ o n*) 1)	(o (n* 1) 88))
  (check-exn exn:fail:contract? (λ () ((∘ o n*))))
  (check-exn exn:fail:contract? (λ () ((∘ o n*) 0 1 2)))
  (check-equal? ((∘ o n*) 1 2)	(o (n* 1) 2))
  (check-exn exn:fail:contract? (λ () ((∘ o u*))))
  (check-exn exn:fail:contract? (λ () ((∘ o u*) 0 1 2)))
  (check-equal? ((∘ o u*) 1)	(o (u* 1) 88))
  (check-exn exn:fail:contract? (λ () ((∘ o u*))))
  (check-exn exn:fail:contract? (λ () ((∘ o u*) 0 1 2)))
  (check-equal? ((∘ o u*) 1 2)	(o (u* 1) 2))
  (check-exn exn:fail:contract? (λ () ((∘ o b*) 0)))
  (check-exn exn:fail:contract? (λ () ((∘ o b*) 0 1 2 3)))
  (check-equal? ((∘ o b*) 1 2)	(o (b* 1 2) 88))
  (check-exn exn:fail:contract? (λ () ((∘ o b*) 0)))
  (check-exn exn:fail:contract? (λ () ((∘ o b*) 0 1 2 3)))
  (check-equal? ((∘ o b*) 1 2 3)	(o (b* 1 2) 3))
  (check-exn exn:fail:contract? (λ () ((∘ o v))))
  (check-exn exn:fail:contract? (λ () ((∘ o v) 0 1 2)))
  (check-equal? ((∘ o v) 1)	(o (v 1) 88))
  (check-exn exn:fail:contract? (λ () ((∘ o v))))
  (check-exn exn:fail:contract? (λ () ((∘ o v) 0 1 2)))
  (check-equal? ((∘ o v) 1 2)	(o (v 1) 2))
  (check-exn exn:fail:contract? (λ () ((∘ o v*))))
  (check-exn exn:fail:contract? (λ () ((∘ o v*) 0 1 2)))
  (check-equal? ((∘ o v*) 1)	(o (v* 1) 88))
  (check-exn exn:fail:contract? (λ () ((∘ o v*))))
  (check-exn exn:fail:contract? (λ () ((∘ o v*) 0 1 2)))
  (check-equal? ((∘ o v*) 1 2)	(o (v* 1) 2))
  (check-exn exn:fail:contract? (λ () ((∘ o o))))
  (check-exn exn:fail:contract? (λ () ((∘ o o) 0 1 2)))
  (check-equal? ((∘ o o) 1)	(o (o 1 88) 88))
  (check-exn exn:fail:contract? (λ () ((∘ o o))))
  (check-exn exn:fail:contract? (λ () ((∘ o o) 0 1 2)))
  (check-equal? ((∘ o o) 1 2)	(o (o 1 88) 2))
))
(provide two-functions)
(define (right-identity)
(test-case "id is the right unit"
  (check-equal? ((∘ u (λ (x) x)) 1)	(u 1))
  (check-equal? ((∘ b (λ (x) x)) 1 2)	(b 1 2))
  (check-equal? ((∘ t (λ (x) x)) 1 2 3)	(t 1 2 3))
  (check-equal? ((∘ u* (λ (x) x)) 1)	(u* 1))
  (check-equal? ((∘ u* (λ (x) x)) 1 2)	(u* 1 2))
  (check-equal? ((∘ b* (λ (x) x)) 1 2)	(b* 1 2))
  (check-equal? ((∘ b* (λ (x) x)) 1 2 3)	(b* 1 2 3))
  (check-equal? ((∘ v (λ (x) x)) 1)	(v 1))
  (check-equal? ((∘ v (λ (x) x)) 1 2)	(v 1 2))
  (check-equal? ((∘ v (λ (x) x)) 1 2 3 4)	(v 1 2 3 4))
  (check-equal? ((∘ v* (λ (x) x)) 1)	(v* 1))
  (check-equal? ((∘ v* (λ (x) x)) 1 2)	(v* 1 2))
  (check-equal? ((∘ v* (λ (x) x)) 1 2 3)	(v* 1 2 3))
  (check-equal? ((∘ v* (λ (x) x)) 1 2 3 4)	(v* 1 2 3 4))
  (check-equal? ((∘ o (λ (x) x)) 1)	(o 1 88))
  (check-equal? ((∘ o (λ (x) x)) 1 2)	(o 1 2))
))
(provide right-identity)
(define (left-identity)
(test-case "id is the left unit"
  (check-equal? ((∘ (λ (x) x) n))	(n))
  (check-equal? ((∘ (λ (x) x) u) 1)	(u 1))
  (check-equal? ((∘ (λ (x) x) b) 1 2)	(b 1 2))
  (check-equal? ((∘ (λ (x) x) t) 1 2 3)	(t 1 2 3))
  (check-equal? ((∘ (λ (x) x) n*))	(n*))
  (check-equal? ((∘ (λ (x) x) n*) 1)	(n* 1))
  (check-equal? ((∘ (λ (x) x) u*) 1)	(u* 1))
  (check-equal? ((∘ (λ (x) x) u*) 1 2)	(u* 1 2))
  (check-equal? ((∘ (λ (x) x) b*) 1 2)	(b* 1 2))
  (check-equal? ((∘ (λ (x) x) b*) 1 2 3)	(b* 1 2 3))
  (check-equal? ((∘ (λ (x) x) v) 1)	(v 1))
  (check-equal? ((∘ (λ (x) x) v) 1 2)	(v 1 2))
  (check-equal? ((∘ (λ (x) x) v) 1 2 3 4)	(v 1 2 3 4))
  (check-equal? ((∘ (λ (x) x) v*) 1)	(v* 1))
  (check-equal? ((∘ (λ (x) x) v*) 1 2)	(v* 1 2))
  (check-equal? ((∘ (λ (x) x) v*) 1 2 3)	(v* 1 2 3))
  (check-equal? ((∘ (λ (x) x) v*) 1 2 3 4)	(v* 1 2 3 4))
  (check-equal? ((∘ (λ (x) x) o) 1)	(o 1 88))
  (check-equal? ((∘ (λ (x) x) o) 1 2)	(o 1 2))
))
(provide left-identity)
(define (associativity)
(test-case "associativity for fixed-arity functions"
  (check-equal? ((∘ u (∘ u n)))	((∘ (∘ u u) n)))
  (check-equal? ((∘ u (∘ u u)) 1)	((∘ (∘ u u) u) 1))
  (check-equal? ((∘ u (∘ u b)) 1 2)	((∘ (∘ u u) b) 1 2))
  (check-equal? ((∘ u (∘ u t)) 1 2 3)	((∘ (∘ u u) t) 1 2 3))
  (check-equal? ((∘ u (∘ u n*)))	((∘ (∘ u u) n*)))
  (check-equal? ((∘ u (∘ u n*)) 1)	((∘ (∘ u u) n*) 1))
  (check-equal? ((∘ u (∘ u u*)) 1)	((∘ (∘ u u) u*) 1))
  (check-equal? ((∘ u (∘ u u*)) 1 2)	((∘ (∘ u u) u*) 1 2))
  (check-equal? ((∘ u (∘ u b*)) 1 2)	((∘ (∘ u u) b*) 1 2))
  (check-equal? ((∘ u (∘ u b*)) 1 2 3)	((∘ (∘ u u) b*) 1 2 3))
  (check-equal? ((∘ u (∘ u v)) 1)	((∘ (∘ u u) v) 1))
  (check-equal? ((∘ u (∘ u v)) 1 2)	((∘ (∘ u u) v) 1 2))
  (check-equal? ((∘ u (∘ u v)) 1 2 3 4)	((∘ (∘ u u) v) 1 2 3 4))
  (check-equal? ((∘ u (∘ u v*)) 1)	((∘ (∘ u u) v*) 1))
  (check-equal? ((∘ u (∘ u v*)) 1 2)	((∘ (∘ u u) v*) 1 2))
  (check-equal? ((∘ u (∘ u v*)) 1 2 3)	((∘ (∘ u u) v*) 1 2 3))
  (check-equal? ((∘ u (∘ u v*)) 1 2 3 4)	((∘ (∘ u u) v*) 1 2 3 4))
  (check-equal? ((∘ u (∘ u o)) 1)	((∘ (∘ u u) o) 1))
  (check-equal? ((∘ u (∘ u o)) 1 2)	((∘ (∘ u u) o) 1 2))
  (check-equal? ((∘ u (∘ b n)) 1)	((∘ (∘ u b) n) 1))
  (check-equal? ((∘ u (∘ b u)) 1 2)	((∘ (∘ u b) u) 1 2))
  (check-equal? ((∘ u (∘ b b)) 1 2 3)	((∘ (∘ u b) b) 1 2 3))
  (check-equal? ((∘ u (∘ b t)) 1 2 3 4)	((∘ (∘ u b) t) 1 2 3 4))
  (check-equal? ((∘ u (∘ b n*)) 1 2)	((∘ (∘ u b) n*) 1 2))
  (check-equal? ((∘ u (∘ b u*)) 1 2)	((∘ (∘ u b) u*) 1 2))
  (check-equal? ((∘ u (∘ b b*)) 1 2 3)	((∘ (∘ u b) b*) 1 2 3))
  (check-equal? ((∘ u (∘ b v)) 1 2)	((∘ (∘ u b) v) 1 2))
  (check-equal? ((∘ u (∘ b v*)) 1 2)	((∘ (∘ u b) v*) 1 2))
  (check-equal? ((∘ u (∘ b o)) 1 2)	((∘ (∘ u b) o) 1 2))
  (check-equal? ((∘ u (∘ t n)) 1 2)	((∘ (∘ u t) n) 1 2))
  (check-equal? ((∘ u (∘ t u)) 1 2 3)	((∘ (∘ u t) u) 1 2 3))
  (check-equal? ((∘ u (∘ t b)) 1 2 3 4)	((∘ (∘ u t) b) 1 2 3 4))
  (check-equal? ((∘ u (∘ t t)) 1 2 3 4 5)	((∘ (∘ u t) t) 1 2 3 4 5))
  (check-equal? ((∘ u (∘ t n*)) 1 2 3)	((∘ (∘ u t) n*) 1 2 3))
  (check-equal? ((∘ u (∘ t u*)) 1 2 3)	((∘ (∘ u t) u*) 1 2 3))
  (check-equal? ((∘ u (∘ t b*)) 1 2 3 4)	((∘ (∘ u t) b*) 1 2 3 4))
  (check-equal? ((∘ u (∘ t v)) 1 2 3)	((∘ (∘ u t) v) 1 2 3))
  (check-equal? ((∘ u (∘ t v*)) 1 2 3)	((∘ (∘ u t) v*) 1 2 3))
  (check-equal? ((∘ u (∘ t o)) 1 2 3)	((∘ (∘ u t) o) 1 2 3))
  (check-equal? ((∘ u (∘ v n)))	((∘ (∘ u v) n)))
  (check-equal? ((∘ u (∘ v n)) 1)	((∘ (∘ u v) n) 1))
  (check-equal? ((∘ u (∘ v n)) 1 2 3)	((∘ (∘ u v) n) 1 2 3))
  (check-equal? ((∘ u (∘ v u)) 1)	((∘ (∘ u v) u) 1))
  (check-equal? ((∘ u (∘ v u)) 1 2)	((∘ (∘ u v) u) 1 2))
  (check-equal? ((∘ u (∘ v u)) 1 2 3 4)	((∘ (∘ u v) u) 1 2 3 4))
  (check-equal? ((∘ u (∘ v b)) 1 2)	((∘ (∘ u v) b) 1 2))
  (check-equal? ((∘ u (∘ v b)) 1 2 3)	((∘ (∘ u v) b) 1 2 3))
  (check-equal? ((∘ u (∘ v b)) 1 2 3 4 5)	((∘ (∘ u v) b) 1 2 3 4 5))
  (check-equal? ((∘ u (∘ v t)) 1 2 3)	((∘ (∘ u v) t) 1 2 3))
  (check-equal? ((∘ u (∘ v t)) 1 2 3 4)	((∘ (∘ u v) t) 1 2 3 4))
  (check-equal? ((∘ u (∘ v t)) 1 2 3 4 5 6)	((∘ (∘ u v) t) 1 2 3 4 5 6))
  (check-equal? ((∘ u (∘ v n*)) 1)	((∘ (∘ u v) n*) 1))
  (check-equal? ((∘ u (∘ v n*)) 1 2)	((∘ (∘ u v) n*) 1 2))
  (check-equal? ((∘ u (∘ v n*)) 1 2 3 4)	((∘ (∘ u v) n*) 1 2 3 4))
  (check-equal? ((∘ u (∘ v u*)) 1)	((∘ (∘ u v) u*) 1))
  (check-equal? ((∘ u (∘ v u*)) 1 2)	((∘ (∘ u v) u*) 1 2))
  (check-equal? ((∘ u (∘ v u*)) 1 2 3 4)	((∘ (∘ u v) u*) 1 2 3 4))
  (check-equal? ((∘ u (∘ v b*)) 1 2)	((∘ (∘ u v) b*) 1 2))
  (check-equal? ((∘ u (∘ v b*)) 1 2 3)	((∘ (∘ u v) b*) 1 2 3))
  (check-equal? ((∘ u (∘ v b*)) 1 2 3 4 5)	((∘ (∘ u v) b*) 1 2 3 4 5))
  (check-equal? ((∘ u (∘ v v)) 1)	((∘ (∘ u v) v) 1))
  (check-equal? ((∘ u (∘ v v)) 1 2)	((∘ (∘ u v) v) 1 2))
  (check-equal? ((∘ u (∘ v v)) 1 2 3 4)	((∘ (∘ u v) v) 1 2 3 4))
  (check-equal? ((∘ u (∘ v v*)) 1)	((∘ (∘ u v) v*) 1))
  (check-equal? ((∘ u (∘ v v*)) 1 2)	((∘ (∘ u v) v*) 1 2))
  (check-equal? ((∘ u (∘ v v*)) 1 2 3 4)	((∘ (∘ u v) v*) 1 2 3 4))
  (check-equal? ((∘ u (∘ v o)) 1)	((∘ (∘ u v) o) 1))
  (check-equal? ((∘ u (∘ v o)) 1 2)	((∘ (∘ u v) o) 1 2))
  (check-equal? ((∘ u (∘ v o)) 1 2 3 4)	((∘ (∘ u v) o) 1 2 3 4))
  (check-equal? ((∘ u (∘ o n)))	((∘ (∘ u o) n)))
  (check-equal? ((∘ u (∘ o n)) 1)	((∘ (∘ u o) n) 1))
  (check-equal? ((∘ u (∘ o u)) 1)	((∘ (∘ u o) u) 1))
  (check-equal? ((∘ u (∘ o u)) 1 2)	((∘ (∘ u o) u) 1 2))
  (check-equal? ((∘ u (∘ o b)) 1 2)	((∘ (∘ u o) b) 1 2))
  (check-equal? ((∘ u (∘ o b)) 1 2 3)	((∘ (∘ u o) b) 1 2 3))
  (check-equal? ((∘ u (∘ o t)) 1 2 3)	((∘ (∘ u o) t) 1 2 3))
  (check-equal? ((∘ u (∘ o t)) 1 2 3 4)	((∘ (∘ u o) t) 1 2 3 4))
  (check-equal? ((∘ u (∘ o n*)) 1)	((∘ (∘ u o) n*) 1))
  (check-equal? ((∘ u (∘ o n*)) 1 2)	((∘ (∘ u o) n*) 1 2))
  (check-equal? ((∘ u (∘ o u*)) 1)	((∘ (∘ u o) u*) 1))
  (check-equal? ((∘ u (∘ o u*)) 1 2)	((∘ (∘ u o) u*) 1 2))
  (check-equal? ((∘ u (∘ o b*)) 1 2)	((∘ (∘ u o) b*) 1 2))
  (check-equal? ((∘ u (∘ o b*)) 1 2 3)	((∘ (∘ u o) b*) 1 2 3))
  (check-equal? ((∘ u (∘ o v)) 1)	((∘ (∘ u o) v) 1))
  (check-equal? ((∘ u (∘ o v)) 1 2)	((∘ (∘ u o) v) 1 2))
  (check-equal? ((∘ u (∘ o v*)) 1)	((∘ (∘ u o) v*) 1))
  (check-equal? ((∘ u (∘ o v*)) 1 2)	((∘ (∘ u o) v*) 1 2))
  (check-equal? ((∘ u (∘ o o)) 1)	((∘ (∘ u o) o) 1))
  (check-equal? ((∘ u (∘ o o)) 1 2)	((∘ (∘ u o) o) 1 2))
  (check-equal? ((∘ b (∘ u n)) 1)	((∘ (∘ b u) n) 1))
  (check-equal? ((∘ b (∘ u u)) 1 2)	((∘ (∘ b u) u) 1 2))
  (check-equal? ((∘ b (∘ u b)) 1 2 3)	((∘ (∘ b u) b) 1 2 3))
  (check-equal? ((∘ b (∘ u t)) 1 2 3 4)	((∘ (∘ b u) t) 1 2 3 4))
  (check-equal? ((∘ b (∘ u n*)) 1 2)	((∘ (∘ b u) n*) 1 2))
  (check-equal? ((∘ b (∘ u u*)) 1 2)	((∘ (∘ b u) u*) 1 2))
  (check-equal? ((∘ b (∘ u b*)) 1 2 3)	((∘ (∘ b u) b*) 1 2 3))
  (check-equal? ((∘ b (∘ u v)) 1 2)	((∘ (∘ b u) v) 1 2))
  (check-equal? ((∘ b (∘ u v*)) 1 2)	((∘ (∘ b u) v*) 1 2))
  (check-equal? ((∘ b (∘ u o)) 1 2)	((∘ (∘ b u) o) 1 2))
  (check-equal? ((∘ b (∘ b n)) 1 2)	((∘ (∘ b b) n) 1 2))
  (check-equal? ((∘ b (∘ b u)) 1 2 3)	((∘ (∘ b b) u) 1 2 3))
  (check-equal? ((∘ b (∘ b b)) 1 2 3 4)	((∘ (∘ b b) b) 1 2 3 4))
  (check-equal? ((∘ b (∘ b t)) 1 2 3 4 5)	((∘ (∘ b b) t) 1 2 3 4 5))
  (check-equal? ((∘ b (∘ b n*)) 1 2 3)	((∘ (∘ b b) n*) 1 2 3))
  (check-equal? ((∘ b (∘ b u*)) 1 2 3)	((∘ (∘ b b) u*) 1 2 3))
  (check-equal? ((∘ b (∘ b b*)) 1 2 3 4)	((∘ (∘ b b) b*) 1 2 3 4))
  (check-equal? ((∘ b (∘ b v)) 1 2 3)	((∘ (∘ b b) v) 1 2 3))
  (check-equal? ((∘ b (∘ b v*)) 1 2 3)	((∘ (∘ b b) v*) 1 2 3))
  (check-equal? ((∘ b (∘ b o)) 1 2 3)	((∘ (∘ b b) o) 1 2 3))
  (check-equal? ((∘ b (∘ t n)) 1 2 3)	((∘ (∘ b t) n) 1 2 3))
  (check-equal? ((∘ b (∘ t u)) 1 2 3 4)	((∘ (∘ b t) u) 1 2 3 4))
  (check-equal? ((∘ b (∘ t b)) 1 2 3 4 5)	((∘ (∘ b t) b) 1 2 3 4 5))
  (check-equal? ((∘ b (∘ t t)) 1 2 3 4 5 6)	((∘ (∘ b t) t) 1 2 3 4 5 6))
  (check-equal? ((∘ b (∘ t n*)) 1 2 3 4)	((∘ (∘ b t) n*) 1 2 3 4))
  (check-equal? ((∘ b (∘ t u*)) 1 2 3 4)	((∘ (∘ b t) u*) 1 2 3 4))
  (check-equal? ((∘ b (∘ t b*)) 1 2 3 4 5)	((∘ (∘ b t) b*) 1 2 3 4 5))
  (check-equal? ((∘ b (∘ t v)) 1 2 3 4)	((∘ (∘ b t) v) 1 2 3 4))
  (check-equal? ((∘ b (∘ t v*)) 1 2 3 4)	((∘ (∘ b t) v*) 1 2 3 4))
  (check-equal? ((∘ b (∘ t o)) 1 2 3 4)	((∘ (∘ b t) o) 1 2 3 4))
  (check-equal? ((∘ b (∘ v n)) 1)	((∘ (∘ b v) n) 1))
  (check-equal? ((∘ b (∘ v u)) 1 2)	((∘ (∘ b v) u) 1 2))
  (check-equal? ((∘ b (∘ v b)) 1 2 3)	((∘ (∘ b v) b) 1 2 3))
  (check-equal? ((∘ b (∘ v t)) 1 2 3 4)	((∘ (∘ b v) t) 1 2 3 4))
  (check-equal? ((∘ b (∘ v n*)) 1 2)	((∘ (∘ b v) n*) 1 2))
  (check-equal? ((∘ b (∘ v u*)) 1 2)	((∘ (∘ b v) u*) 1 2))
  (check-equal? ((∘ b (∘ v b*)) 1 2 3)	((∘ (∘ b v) b*) 1 2 3))
  (check-equal? ((∘ b (∘ v v)) 1 2)	((∘ (∘ b v) v) 1 2))
  (check-equal? ((∘ b (∘ v v*)) 1 2)	((∘ (∘ b v) v*) 1 2))
  (check-equal? ((∘ b (∘ v o)) 1 2)	((∘ (∘ b v) o) 1 2))
  (check-equal? ((∘ b (∘ o n)) 1)	((∘ (∘ b o) n) 1))
  (check-equal? ((∘ b (∘ o u)) 1 2)	((∘ (∘ b o) u) 1 2))
  (check-equal? ((∘ b (∘ o b)) 1 2 3)	((∘ (∘ b o) b) 1 2 3))
  (check-equal? ((∘ b (∘ o t)) 1 2 3 4)	((∘ (∘ b o) t) 1 2 3 4))
  (check-equal? ((∘ b (∘ o n*)) 1 2)	((∘ (∘ b o) n*) 1 2))
  (check-equal? ((∘ b (∘ o u*)) 1 2)	((∘ (∘ b o) u*) 1 2))
  (check-equal? ((∘ b (∘ o b*)) 1 2 3)	((∘ (∘ b o) b*) 1 2 3))
  (check-equal? ((∘ b (∘ o v)) 1 2)	((∘ (∘ b o) v) 1 2))
  (check-equal? ((∘ b (∘ o v*)) 1 2)	((∘ (∘ b o) v*) 1 2))
  (check-equal? ((∘ b (∘ o o)) 1 2)	((∘ (∘ b o) o) 1 2))
  (check-equal? ((∘ t (∘ u n)) 1 2)	((∘ (∘ t u) n) 1 2))
  (check-equal? ((∘ t (∘ u u)) 1 2 3)	((∘ (∘ t u) u) 1 2 3))
  (check-equal? ((∘ t (∘ u b)) 1 2 3 4)	((∘ (∘ t u) b) 1 2 3 4))
  (check-equal? ((∘ t (∘ u t)) 1 2 3 4 5)	((∘ (∘ t u) t) 1 2 3 4 5))
  (check-equal? ((∘ t (∘ u n*)) 1 2 3)	((∘ (∘ t u) n*) 1 2 3))
  (check-equal? ((∘ t (∘ u u*)) 1 2 3)	((∘ (∘ t u) u*) 1 2 3))
  (check-equal? ((∘ t (∘ u b*)) 1 2 3 4)	((∘ (∘ t u) b*) 1 2 3 4))
  (check-equal? ((∘ t (∘ u v)) 1 2 3)	((∘ (∘ t u) v) 1 2 3))
  (check-equal? ((∘ t (∘ u v*)) 1 2 3)	((∘ (∘ t u) v*) 1 2 3))
  (check-equal? ((∘ t (∘ u o)) 1 2 3)	((∘ (∘ t u) o) 1 2 3))
  (check-equal? ((∘ t (∘ b n)) 1 2 3)	((∘ (∘ t b) n) 1 2 3))
  (check-equal? ((∘ t (∘ b u)) 1 2 3 4)	((∘ (∘ t b) u) 1 2 3 4))
  (check-equal? ((∘ t (∘ b b)) 1 2 3 4 5)	((∘ (∘ t b) b) 1 2 3 4 5))
  (check-equal? ((∘ t (∘ b t)) 1 2 3 4 5 6)	((∘ (∘ t b) t) 1 2 3 4 5 6))
  (check-equal? ((∘ t (∘ b n*)) 1 2 3 4)	((∘ (∘ t b) n*) 1 2 3 4))
  (check-equal? ((∘ t (∘ b u*)) 1 2 3 4)	((∘ (∘ t b) u*) 1 2 3 4))
  (check-equal? ((∘ t (∘ b b*)) 1 2 3 4 5)	((∘ (∘ t b) b*) 1 2 3 4 5))
  (check-equal? ((∘ t (∘ b v)) 1 2 3 4)	((∘ (∘ t b) v) 1 2 3 4))
  (check-equal? ((∘ t (∘ b v*)) 1 2 3 4)	((∘ (∘ t b) v*) 1 2 3 4))
  (check-equal? ((∘ t (∘ b o)) 1 2 3 4)	((∘ (∘ t b) o) 1 2 3 4))
  (check-equal? ((∘ t (∘ t n)) 1 2 3 4)	((∘ (∘ t t) n) 1 2 3 4))
  (check-equal? ((∘ t (∘ t u)) 1 2 3 4 5)	((∘ (∘ t t) u) 1 2 3 4 5))
  (check-equal? ((∘ t (∘ t b)) 1 2 3 4 5 6)	((∘ (∘ t t) b) 1 2 3 4 5 6))
  (check-equal? ((∘ t (∘ t t)) 1 2 3 4 5 6 7)	((∘ (∘ t t) t) 1 2 3 4 5 6 7))
  (check-equal? ((∘ t (∘ t n*)) 1 2 3 4 5)	((∘ (∘ t t) n*) 1 2 3 4 5))
  (check-equal? ((∘ t (∘ t u*)) 1 2 3 4 5)	((∘ (∘ t t) u*) 1 2 3 4 5))
  (check-equal? ((∘ t (∘ t b*)) 1 2 3 4 5 6)	((∘ (∘ t t) b*) 1 2 3 4 5 6))
  (check-equal? ((∘ t (∘ t v)) 1 2 3 4 5)	((∘ (∘ t t) v) 1 2 3 4 5))
  (check-equal? ((∘ t (∘ t v*)) 1 2 3 4 5)	((∘ (∘ t t) v*) 1 2 3 4 5))
  (check-equal? ((∘ t (∘ t o)) 1 2 3 4 5)	((∘ (∘ t t) o) 1 2 3 4 5))
  (check-equal? ((∘ t (∘ v n)) 1 2)	((∘ (∘ t v) n) 1 2))
  (check-equal? ((∘ t (∘ v u)) 1 2 3)	((∘ (∘ t v) u) 1 2 3))
  (check-equal? ((∘ t (∘ v b)) 1 2 3 4)	((∘ (∘ t v) b) 1 2 3 4))
  (check-equal? ((∘ t (∘ v t)) 1 2 3 4 5)	((∘ (∘ t v) t) 1 2 3 4 5))
  (check-equal? ((∘ t (∘ v n*)) 1 2 3)	((∘ (∘ t v) n*) 1 2 3))
  (check-equal? ((∘ t (∘ v u*)) 1 2 3)	((∘ (∘ t v) u*) 1 2 3))
  (check-equal? ((∘ t (∘ v b*)) 1 2 3 4)	((∘ (∘ t v) b*) 1 2 3 4))
  (check-equal? ((∘ t (∘ v v)) 1 2 3)	((∘ (∘ t v) v) 1 2 3))
  (check-equal? ((∘ t (∘ v v*)) 1 2 3)	((∘ (∘ t v) v*) 1 2 3))
  (check-equal? ((∘ t (∘ v o)) 1 2 3)	((∘ (∘ t v) o) 1 2 3))
  (check-equal? ((∘ t (∘ o n)) 1 2)	((∘ (∘ t o) n) 1 2))
  (check-equal? ((∘ t (∘ o u)) 1 2 3)	((∘ (∘ t o) u) 1 2 3))
  (check-equal? ((∘ t (∘ o b)) 1 2 3 4)	((∘ (∘ t o) b) 1 2 3 4))
  (check-equal? ((∘ t (∘ o t)) 1 2 3 4 5)	((∘ (∘ t o) t) 1 2 3 4 5))
  (check-equal? ((∘ t (∘ o n*)) 1 2 3)	((∘ (∘ t o) n*) 1 2 3))
  (check-equal? ((∘ t (∘ o u*)) 1 2 3)	((∘ (∘ t o) u*) 1 2 3))
  (check-equal? ((∘ t (∘ o b*)) 1 2 3 4)	((∘ (∘ t o) b*) 1 2 3 4))
  (check-equal? ((∘ t (∘ o v)) 1 2 3)	((∘ (∘ t o) v) 1 2 3))
  (check-equal? ((∘ t (∘ o v*)) 1 2 3)	((∘ (∘ t o) v*) 1 2 3))
  (check-equal? ((∘ t (∘ o o)) 1 2 3)	((∘ (∘ t o) o) 1 2 3))
  (check-equal? ((∘ u* (∘ u n)))	((∘ (∘ u* u) n)))
  (check-equal? ((∘ u* (∘ u n)) 1)	((∘ (∘ u* u) n) 1))
  (check-equal? ((∘ u* (∘ u u)) 1)	((∘ (∘ u* u) u) 1))
  (check-equal? ((∘ u* (∘ u u)) 1 2)	((∘ (∘ u* u) u) 1 2))
  (check-equal? ((∘ u* (∘ u b)) 1 2)	((∘ (∘ u* u) b) 1 2))
  (check-equal? ((∘ u* (∘ u b)) 1 2 3)	((∘ (∘ u* u) b) 1 2 3))
  (check-equal? ((∘ u* (∘ u t)) 1 2 3)	((∘ (∘ u* u) t) 1 2 3))
  (check-equal? ((∘ u* (∘ u t)) 1 2 3 4)	((∘ (∘ u* u) t) 1 2 3 4))
  (check-equal? ((∘ u* (∘ u n*)) 1)	((∘ (∘ u* u) n*) 1))
  (check-equal? ((∘ u* (∘ u n*)) 1 2)	((∘ (∘ u* u) n*) 1 2))
  (check-equal? ((∘ u* (∘ u u*)) 1)	((∘ (∘ u* u) u*) 1))
  (check-equal? ((∘ u* (∘ u u*)) 1 2)	((∘ (∘ u* u) u*) 1 2))
  (check-equal? ((∘ u* (∘ u b*)) 1 2)	((∘ (∘ u* u) b*) 1 2))
  (check-equal? ((∘ u* (∘ u b*)) 1 2 3)	((∘ (∘ u* u) b*) 1 2 3))
  (check-equal? ((∘ u* (∘ u v)) 1)	((∘ (∘ u* u) v) 1))
  (check-equal? ((∘ u* (∘ u v)) 1 2)	((∘ (∘ u* u) v) 1 2))
  (check-equal? ((∘ u* (∘ u v*)) 1)	((∘ (∘ u* u) v*) 1))
  (check-equal? ((∘ u* (∘ u v*)) 1 2)	((∘ (∘ u* u) v*) 1 2))
  (check-equal? ((∘ u* (∘ u o)) 1)	((∘ (∘ u* u) o) 1))
  (check-equal? ((∘ u* (∘ u o)) 1 2)	((∘ (∘ u* u) o) 1 2))
  (check-equal? ((∘ u* (∘ b n)) 1)	((∘ (∘ u* b) n) 1))
  (check-equal? ((∘ u* (∘ b n)) 1 2)	((∘ (∘ u* b) n) 1 2))
  (check-equal? ((∘ u* (∘ b u)) 1 2)	((∘ (∘ u* b) u) 1 2))
  (check-equal? ((∘ u* (∘ b u)) 1 2 3)	((∘ (∘ u* b) u) 1 2 3))
  (check-equal? ((∘ u* (∘ b b)) 1 2 3)	((∘ (∘ u* b) b) 1 2 3))
  (check-equal? ((∘ u* (∘ b b)) 1 2 3 4)	((∘ (∘ u* b) b) 1 2 3 4))
  (check-equal? ((∘ u* (∘ b t)) 1 2 3 4)	((∘ (∘ u* b) t) 1 2 3 4))
  (check-equal? ((∘ u* (∘ b t)) 1 2 3 4 5)	((∘ (∘ u* b) t) 1 2 3 4 5))
  (check-equal? ((∘ u* (∘ b n*)) 1 2)	((∘ (∘ u* b) n*) 1 2))
  (check-equal? ((∘ u* (∘ b n*)) 1 2 3)	((∘ (∘ u* b) n*) 1 2 3))
  (check-equal? ((∘ u* (∘ b u*)) 1 2)	((∘ (∘ u* b) u*) 1 2))
  (check-equal? ((∘ u* (∘ b u*)) 1 2 3)	((∘ (∘ u* b) u*) 1 2 3))
  (check-equal? ((∘ u* (∘ b b*)) 1 2 3)	((∘ (∘ u* b) b*) 1 2 3))
  (check-equal? ((∘ u* (∘ b b*)) 1 2 3 4)	((∘ (∘ u* b) b*) 1 2 3 4))
  (check-equal? ((∘ u* (∘ b v)) 1 2)	((∘ (∘ u* b) v) 1 2))
  (check-equal? ((∘ u* (∘ b v)) 1 2 3)	((∘ (∘ u* b) v) 1 2 3))
  (check-equal? ((∘ u* (∘ b v*)) 1 2)	((∘ (∘ u* b) v*) 1 2))
  (check-equal? ((∘ u* (∘ b v*)) 1 2 3)	((∘ (∘ u* b) v*) 1 2 3))
  (check-equal? ((∘ u* (∘ b o)) 1 2)	((∘ (∘ u* b) o) 1 2))
  (check-equal? ((∘ u* (∘ b o)) 1 2 3)	((∘ (∘ u* b) o) 1 2 3))
  (check-equal? ((∘ u* (∘ t n)) 1 2)	((∘ (∘ u* t) n) 1 2))
  (check-equal? ((∘ u* (∘ t n)) 1 2 3)	((∘ (∘ u* t) n) 1 2 3))
  (check-equal? ((∘ u* (∘ t u)) 1 2 3)	((∘ (∘ u* t) u) 1 2 3))
  (check-equal? ((∘ u* (∘ t u)) 1 2 3 4)	((∘ (∘ u* t) u) 1 2 3 4))
  (check-equal? ((∘ u* (∘ t b)) 1 2 3 4)	((∘ (∘ u* t) b) 1 2 3 4))
  (check-equal? ((∘ u* (∘ t b)) 1 2 3 4 5)	((∘ (∘ u* t) b) 1 2 3 4 5))
  (check-equal? ((∘ u* (∘ t t)) 1 2 3 4 5)	((∘ (∘ u* t) t) 1 2 3 4 5))
  (check-equal? ((∘ u* (∘ t t)) 1 2 3 4 5 6)	((∘ (∘ u* t) t) 1 2 3 4 5 6))
  (check-equal? ((∘ u* (∘ t n*)) 1 2 3)	((∘ (∘ u* t) n*) 1 2 3))
  (check-equal? ((∘ u* (∘ t n*)) 1 2 3 4)	((∘ (∘ u* t) n*) 1 2 3 4))
  (check-equal? ((∘ u* (∘ t u*)) 1 2 3)	((∘ (∘ u* t) u*) 1 2 3))
  (check-equal? ((∘ u* (∘ t u*)) 1 2 3 4)	((∘ (∘ u* t) u*) 1 2 3 4))
  (check-equal? ((∘ u* (∘ t b*)) 1 2 3 4)	((∘ (∘ u* t) b*) 1 2 3 4))
  (check-equal? ((∘ u* (∘ t b*)) 1 2 3 4 5)	((∘ (∘ u* t) b*) 1 2 3 4 5))
  (check-equal? ((∘ u* (∘ t v)) 1 2 3)	((∘ (∘ u* t) v) 1 2 3))
  (check-equal? ((∘ u* (∘ t v)) 1 2 3 4)	((∘ (∘ u* t) v) 1 2 3 4))
  (check-equal? ((∘ u* (∘ t v*)) 1 2 3)	((∘ (∘ u* t) v*) 1 2 3))
  (check-equal? ((∘ u* (∘ t v*)) 1 2 3 4)	((∘ (∘ u* t) v*) 1 2 3 4))
  (check-equal? ((∘ u* (∘ t o)) 1 2 3)	((∘ (∘ u* t) o) 1 2 3))
  (check-equal? ((∘ u* (∘ t o)) 1 2 3 4)	((∘ (∘ u* t) o) 1 2 3 4))
  (check-equal? ((∘ u* (∘ v n)))	((∘ (∘ u* v) n)))
  (check-equal? ((∘ u* (∘ v n)) 1)	((∘ (∘ u* v) n) 1))
  (check-equal? ((∘ u* (∘ v u)) 1)	((∘ (∘ u* v) u) 1))
  (check-equal? ((∘ u* (∘ v u)) 1 2)	((∘ (∘ u* v) u) 1 2))
  (check-equal? ((∘ u* (∘ v b)) 1 2)	((∘ (∘ u* v) b) 1 2))
  (check-equal? ((∘ u* (∘ v b)) 1 2 3)	((∘ (∘ u* v) b) 1 2 3))
  (check-equal? ((∘ u* (∘ v t)) 1 2 3)	((∘ (∘ u* v) t) 1 2 3))
  (check-equal? ((∘ u* (∘ v t)) 1 2 3 4)	((∘ (∘ u* v) t) 1 2 3 4))
  (check-equal? ((∘ u* (∘ v n*)) 1)	((∘ (∘ u* v) n*) 1))
  (check-equal? ((∘ u* (∘ v n*)) 1 2)	((∘ (∘ u* v) n*) 1 2))
  (check-equal? ((∘ u* (∘ v u*)) 1)	((∘ (∘ u* v) u*) 1))
  (check-equal? ((∘ u* (∘ v u*)) 1 2)	((∘ (∘ u* v) u*) 1 2))
  (check-equal? ((∘ u* (∘ v b*)) 1 2)	((∘ (∘ u* v) b*) 1 2))
  (check-equal? ((∘ u* (∘ v b*)) 1 2 3)	((∘ (∘ u* v) b*) 1 2 3))
  (check-equal? ((∘ u* (∘ v v)) 1)	((∘ (∘ u* v) v) 1))
  (check-equal? ((∘ u* (∘ v v)) 1 2)	((∘ (∘ u* v) v) 1 2))
  (check-equal? ((∘ u* (∘ v v*)) 1)	((∘ (∘ u* v) v*) 1))
  (check-equal? ((∘ u* (∘ v v*)) 1 2)	((∘ (∘ u* v) v*) 1 2))
  (check-equal? ((∘ u* (∘ v o)) 1)	((∘ (∘ u* v) o) 1))
  (check-equal? ((∘ u* (∘ v o)) 1 2)	((∘ (∘ u* v) o) 1 2))
  (check-equal? ((∘ u* (∘ o n)))	((∘ (∘ u* o) n)))
  (check-equal? ((∘ u* (∘ o n)) 1)	((∘ (∘ u* o) n) 1))
  (check-equal? ((∘ u* (∘ o u)) 1)	((∘ (∘ u* o) u) 1))
  (check-equal? ((∘ u* (∘ o u)) 1 2)	((∘ (∘ u* o) u) 1 2))
  (check-equal? ((∘ u* (∘ o b)) 1 2)	((∘ (∘ u* o) b) 1 2))
  (check-equal? ((∘ u* (∘ o b)) 1 2 3)	((∘ (∘ u* o) b) 1 2 3))
  (check-equal? ((∘ u* (∘ o t)) 1 2 3)	((∘ (∘ u* o) t) 1 2 3))
  (check-equal? ((∘ u* (∘ o t)) 1 2 3 4)	((∘ (∘ u* o) t) 1 2 3 4))
  (check-equal? ((∘ u* (∘ o n*)) 1)	((∘ (∘ u* o) n*) 1))
  (check-equal? ((∘ u* (∘ o n*)) 1 2)	((∘ (∘ u* o) n*) 1 2))
  (check-equal? ((∘ u* (∘ o u*)) 1)	((∘ (∘ u* o) u*) 1))
  (check-equal? ((∘ u* (∘ o u*)) 1 2)	((∘ (∘ u* o) u*) 1 2))
  (check-equal? ((∘ u* (∘ o b*)) 1 2)	((∘ (∘ u* o) b*) 1 2))
  (check-equal? ((∘ u* (∘ o b*)) 1 2 3)	((∘ (∘ u* o) b*) 1 2 3))
  (check-equal? ((∘ u* (∘ o v)) 1)	((∘ (∘ u* o) v) 1))
  (check-equal? ((∘ u* (∘ o v)) 1 2)	((∘ (∘ u* o) v) 1 2))
  (check-equal? ((∘ u* (∘ o v*)) 1)	((∘ (∘ u* o) v*) 1))
  (check-equal? ((∘ u* (∘ o v*)) 1 2)	((∘ (∘ u* o) v*) 1 2))
  (check-equal? ((∘ u* (∘ o o)) 1)	((∘ (∘ u* o) o) 1))
  (check-equal? ((∘ u* (∘ o o)) 1 2)	((∘ (∘ u* o) o) 1 2))
  (check-equal? ((∘ b* (∘ u n)) 1)	((∘ (∘ b* u) n) 1))
  (check-equal? ((∘ b* (∘ u n)) 1 2)	((∘ (∘ b* u) n) 1 2))
  (check-equal? ((∘ b* (∘ u u)) 1 2)	((∘ (∘ b* u) u) 1 2))
  (check-equal? ((∘ b* (∘ u u)) 1 2 3)	((∘ (∘ b* u) u) 1 2 3))
  (check-equal? ((∘ b* (∘ u b)) 1 2 3)	((∘ (∘ b* u) b) 1 2 3))
  (check-equal? ((∘ b* (∘ u b)) 1 2 3 4)	((∘ (∘ b* u) b) 1 2 3 4))
  (check-equal? ((∘ b* (∘ u t)) 1 2 3 4)	((∘ (∘ b* u) t) 1 2 3 4))
  (check-equal? ((∘ b* (∘ u t)) 1 2 3 4 5)	((∘ (∘ b* u) t) 1 2 3 4 5))
  (check-equal? ((∘ b* (∘ u n*)) 1 2)	((∘ (∘ b* u) n*) 1 2))
  (check-equal? ((∘ b* (∘ u n*)) 1 2 3)	((∘ (∘ b* u) n*) 1 2 3))
  (check-equal? ((∘ b* (∘ u u*)) 1 2)	((∘ (∘ b* u) u*) 1 2))
  (check-equal? ((∘ b* (∘ u u*)) 1 2 3)	((∘ (∘ b* u) u*) 1 2 3))
  (check-equal? ((∘ b* (∘ u b*)) 1 2 3)	((∘ (∘ b* u) b*) 1 2 3))
  (check-equal? ((∘ b* (∘ u b*)) 1 2 3 4)	((∘ (∘ b* u) b*) 1 2 3 4))
  (check-equal? ((∘ b* (∘ u v)) 1 2)	((∘ (∘ b* u) v) 1 2))
  (check-equal? ((∘ b* (∘ u v)) 1 2 3)	((∘ (∘ b* u) v) 1 2 3))
  (check-equal? ((∘ b* (∘ u v*)) 1 2)	((∘ (∘ b* u) v*) 1 2))
  (check-equal? ((∘ b* (∘ u v*)) 1 2 3)	((∘ (∘ b* u) v*) 1 2 3))
  (check-equal? ((∘ b* (∘ u o)) 1 2)	((∘ (∘ b* u) o) 1 2))
  (check-equal? ((∘ b* (∘ u o)) 1 2 3)	((∘ (∘ b* u) o) 1 2 3))
  (check-equal? ((∘ b* (∘ b n)) 1 2)	((∘ (∘ b* b) n) 1 2))
  (check-equal? ((∘ b* (∘ b n)) 1 2 3)	((∘ (∘ b* b) n) 1 2 3))
  (check-equal? ((∘ b* (∘ b u)) 1 2 3)	((∘ (∘ b* b) u) 1 2 3))
  (check-equal? ((∘ b* (∘ b u)) 1 2 3 4)	((∘ (∘ b* b) u) 1 2 3 4))
  (check-equal? ((∘ b* (∘ b b)) 1 2 3 4)	((∘ (∘ b* b) b) 1 2 3 4))
  (check-equal? ((∘ b* (∘ b b)) 1 2 3 4 5)	((∘ (∘ b* b) b) 1 2 3 4 5))
  (check-equal? ((∘ b* (∘ b t)) 1 2 3 4 5)	((∘ (∘ b* b) t) 1 2 3 4 5))
  (check-equal? ((∘ b* (∘ b t)) 1 2 3 4 5 6)	((∘ (∘ b* b) t) 1 2 3 4 5 6))
  (check-equal? ((∘ b* (∘ b n*)) 1 2 3)	((∘ (∘ b* b) n*) 1 2 3))
  (check-equal? ((∘ b* (∘ b n*)) 1 2 3 4)	((∘ (∘ b* b) n*) 1 2 3 4))
  (check-equal? ((∘ b* (∘ b u*)) 1 2 3)	((∘ (∘ b* b) u*) 1 2 3))
  (check-equal? ((∘ b* (∘ b u*)) 1 2 3 4)	((∘ (∘ b* b) u*) 1 2 3 4))
  (check-equal? ((∘ b* (∘ b b*)) 1 2 3 4)	((∘ (∘ b* b) b*) 1 2 3 4))
  (check-equal? ((∘ b* (∘ b b*)) 1 2 3 4 5)	((∘ (∘ b* b) b*) 1 2 3 4 5))
  (check-equal? ((∘ b* (∘ b v)) 1 2 3)	((∘ (∘ b* b) v) 1 2 3))
  (check-equal? ((∘ b* (∘ b v)) 1 2 3 4)	((∘ (∘ b* b) v) 1 2 3 4))
  (check-equal? ((∘ b* (∘ b v*)) 1 2 3)	((∘ (∘ b* b) v*) 1 2 3))
  (check-equal? ((∘ b* (∘ b v*)) 1 2 3 4)	((∘ (∘ b* b) v*) 1 2 3 4))
  (check-equal? ((∘ b* (∘ b o)) 1 2 3)	((∘ (∘ b* b) o) 1 2 3))
  (check-equal? ((∘ b* (∘ b o)) 1 2 3 4)	((∘ (∘ b* b) o) 1 2 3 4))
  (check-equal? ((∘ b* (∘ t n)) 1 2 3)	((∘ (∘ b* t) n) 1 2 3))
  (check-equal? ((∘ b* (∘ t n)) 1 2 3 4)	((∘ (∘ b* t) n) 1 2 3 4))
  (check-equal? ((∘ b* (∘ t u)) 1 2 3 4)	((∘ (∘ b* t) u) 1 2 3 4))
  (check-equal? ((∘ b* (∘ t u)) 1 2 3 4 5)	((∘ (∘ b* t) u) 1 2 3 4 5))
  (check-equal? ((∘ b* (∘ t b)) 1 2 3 4 5)	((∘ (∘ b* t) b) 1 2 3 4 5))
  (check-equal? ((∘ b* (∘ t b)) 1 2 3 4 5 6)	((∘ (∘ b* t) b) 1 2 3 4 5 6))
  (check-equal? ((∘ b* (∘ t t)) 1 2 3 4 5 6)	((∘ (∘ b* t) t) 1 2 3 4 5 6))
  (check-equal? ((∘ b* (∘ t t)) 1 2 3 4 5 6 7)	((∘ (∘ b* t) t) 1 2 3 4 5 6 7))
  (check-equal? ((∘ b* (∘ t n*)) 1 2 3 4)	((∘ (∘ b* t) n*) 1 2 3 4))
  (check-equal? ((∘ b* (∘ t n*)) 1 2 3 4 5)	((∘ (∘ b* t) n*) 1 2 3 4 5))
  (check-equal? ((∘ b* (∘ t u*)) 1 2 3 4)	((∘ (∘ b* t) u*) 1 2 3 4))
  (check-equal? ((∘ b* (∘ t u*)) 1 2 3 4 5)	((∘ (∘ b* t) u*) 1 2 3 4 5))
  (check-equal? ((∘ b* (∘ t b*)) 1 2 3 4 5)	((∘ (∘ b* t) b*) 1 2 3 4 5))
  (check-equal? ((∘ b* (∘ t b*)) 1 2 3 4 5 6)	((∘ (∘ b* t) b*) 1 2 3 4 5 6))
  (check-equal? ((∘ b* (∘ t v)) 1 2 3 4)	((∘ (∘ b* t) v) 1 2 3 4))
  (check-equal? ((∘ b* (∘ t v)) 1 2 3 4 5)	((∘ (∘ b* t) v) 1 2 3 4 5))
  (check-equal? ((∘ b* (∘ t v*)) 1 2 3 4)	((∘ (∘ b* t) v*) 1 2 3 4))
  (check-equal? ((∘ b* (∘ t v*)) 1 2 3 4 5)	((∘ (∘ b* t) v*) 1 2 3 4 5))
  (check-equal? ((∘ b* (∘ t o)) 1 2 3 4)	((∘ (∘ b* t) o) 1 2 3 4))
  (check-equal? ((∘ b* (∘ t o)) 1 2 3 4 5)	((∘ (∘ b* t) o) 1 2 3 4 5))
  (check-equal? ((∘ b* (∘ v n)) 1)	((∘ (∘ b* v) n) 1))
  (check-equal? ((∘ b* (∘ v n)) 1 2)	((∘ (∘ b* v) n) 1 2))
  (check-equal? ((∘ b* (∘ v u)) 1 2)	((∘ (∘ b* v) u) 1 2))
  (check-equal? ((∘ b* (∘ v u)) 1 2 3)	((∘ (∘ b* v) u) 1 2 3))
  (check-equal? ((∘ b* (∘ v b)) 1 2 3)	((∘ (∘ b* v) b) 1 2 3))
  (check-equal? ((∘ b* (∘ v b)) 1 2 3 4)	((∘ (∘ b* v) b) 1 2 3 4))
  (check-equal? ((∘ b* (∘ v t)) 1 2 3 4)	((∘ (∘ b* v) t) 1 2 3 4))
  (check-equal? ((∘ b* (∘ v t)) 1 2 3 4 5)	((∘ (∘ b* v) t) 1 2 3 4 5))
  (check-equal? ((∘ b* (∘ v n*)) 1 2)	((∘ (∘ b* v) n*) 1 2))
  (check-equal? ((∘ b* (∘ v n*)) 1 2 3)	((∘ (∘ b* v) n*) 1 2 3))
  (check-equal? ((∘ b* (∘ v u*)) 1 2)	((∘ (∘ b* v) u*) 1 2))
  (check-equal? ((∘ b* (∘ v u*)) 1 2 3)	((∘ (∘ b* v) u*) 1 2 3))
  (check-equal? ((∘ b* (∘ v b*)) 1 2 3)	((∘ (∘ b* v) b*) 1 2 3))
  (check-equal? ((∘ b* (∘ v b*)) 1 2 3 4)	((∘ (∘ b* v) b*) 1 2 3 4))
  (check-equal? ((∘ b* (∘ v v)) 1 2)	((∘ (∘ b* v) v) 1 2))
  (check-equal? ((∘ b* (∘ v v)) 1 2 3)	((∘ (∘ b* v) v) 1 2 3))
  (check-equal? ((∘ b* (∘ v v*)) 1 2)	((∘ (∘ b* v) v*) 1 2))
  (check-equal? ((∘ b* (∘ v v*)) 1 2 3)	((∘ (∘ b* v) v*) 1 2 3))
  (check-equal? ((∘ b* (∘ v o)) 1 2)	((∘ (∘ b* v) o) 1 2))
  (check-equal? ((∘ b* (∘ v o)) 1 2 3)	((∘ (∘ b* v) o) 1 2 3))
  (check-equal? ((∘ b* (∘ o n)) 1)	((∘ (∘ b* o) n) 1))
  (check-equal? ((∘ b* (∘ o n)) 1 2)	((∘ (∘ b* o) n) 1 2))
  (check-equal? ((∘ b* (∘ o u)) 1 2)	((∘ (∘ b* o) u) 1 2))
  (check-equal? ((∘ b* (∘ o u)) 1 2 3)	((∘ (∘ b* o) u) 1 2 3))
  (check-equal? ((∘ b* (∘ o b)) 1 2 3)	((∘ (∘ b* o) b) 1 2 3))
  (check-equal? ((∘ b* (∘ o b)) 1 2 3 4)	((∘ (∘ b* o) b) 1 2 3 4))
  (check-equal? ((∘ b* (∘ o t)) 1 2 3 4)	((∘ (∘ b* o) t) 1 2 3 4))
  (check-equal? ((∘ b* (∘ o t)) 1 2 3 4 5)	((∘ (∘ b* o) t) 1 2 3 4 5))
  (check-equal? ((∘ b* (∘ o n*)) 1 2)	((∘ (∘ b* o) n*) 1 2))
  (check-equal? ((∘ b* (∘ o n*)) 1 2 3)	((∘ (∘ b* o) n*) 1 2 3))
  (check-equal? ((∘ b* (∘ o u*)) 1 2)	((∘ (∘ b* o) u*) 1 2))
  (check-equal? ((∘ b* (∘ o u*)) 1 2 3)	((∘ (∘ b* o) u*) 1 2 3))
  (check-equal? ((∘ b* (∘ o b*)) 1 2 3)	((∘ (∘ b* o) b*) 1 2 3))
  (check-equal? ((∘ b* (∘ o b*)) 1 2 3 4)	((∘ (∘ b* o) b*) 1 2 3 4))
  (check-equal? ((∘ b* (∘ o v)) 1 2)	((∘ (∘ b* o) v) 1 2))
  (check-equal? ((∘ b* (∘ o v)) 1 2 3)	((∘ (∘ b* o) v) 1 2 3))
  (check-equal? ((∘ b* (∘ o v*)) 1 2)	((∘ (∘ b* o) v*) 1 2))
  (check-equal? ((∘ b* (∘ o v*)) 1 2 3)	((∘ (∘ b* o) v*) 1 2 3))
  (check-equal? ((∘ b* (∘ o o)) 1 2)	((∘ (∘ b* o) o) 1 2))
  (check-equal? ((∘ b* (∘ o o)) 1 2 3)	((∘ (∘ b* o) o) 1 2 3))
  (check-equal? ((∘ v (∘ u n)))	((∘ (∘ v u) n)))
  (check-equal? ((∘ v (∘ u n)) 1)	((∘ (∘ v u) n) 1))
  (check-equal? ((∘ v (∘ u n)) 1 2 3)	((∘ (∘ v u) n) 1 2 3))
  (check-equal? ((∘ v (∘ u u)) 1)	((∘ (∘ v u) u) 1))
  (check-equal? ((∘ v (∘ u u)) 1 2)	((∘ (∘ v u) u) 1 2))
  (check-equal? ((∘ v (∘ u u)) 1 2 3 4)	((∘ (∘ v u) u) 1 2 3 4))
  (check-equal? ((∘ v (∘ u b)) 1 2)	((∘ (∘ v u) b) 1 2))
  (check-equal? ((∘ v (∘ u b)) 1 2 3)	((∘ (∘ v u) b) 1 2 3))
  (check-equal? ((∘ v (∘ u b)) 1 2 3 4 5)	((∘ (∘ v u) b) 1 2 3 4 5))
  (check-equal? ((∘ v (∘ u t)) 1 2 3)	((∘ (∘ v u) t) 1 2 3))
  (check-equal? ((∘ v (∘ u t)) 1 2 3 4)	((∘ (∘ v u) t) 1 2 3 4))
  (check-equal? ((∘ v (∘ u t)) 1 2 3 4 5 6)	((∘ (∘ v u) t) 1 2 3 4 5 6))
  (check-equal? ((∘ v (∘ u n*)) 1)	((∘ (∘ v u) n*) 1))
  (check-equal? ((∘ v (∘ u n*)) 1 2)	((∘ (∘ v u) n*) 1 2))
  (check-equal? ((∘ v (∘ u n*)) 1 2 3 4)	((∘ (∘ v u) n*) 1 2 3 4))
  (check-equal? ((∘ v (∘ u u*)) 1)	((∘ (∘ v u) u*) 1))
  (check-equal? ((∘ v (∘ u u*)) 1 2)	((∘ (∘ v u) u*) 1 2))
  (check-equal? ((∘ v (∘ u u*)) 1 2 3 4)	((∘ (∘ v u) u*) 1 2 3 4))
  (check-equal? ((∘ v (∘ u b*)) 1 2)	((∘ (∘ v u) b*) 1 2))
  (check-equal? ((∘ v (∘ u b*)) 1 2 3)	((∘ (∘ v u) b*) 1 2 3))
  (check-equal? ((∘ v (∘ u b*)) 1 2 3 4 5)	((∘ (∘ v u) b*) 1 2 3 4 5))
  (check-equal? ((∘ v (∘ u v)) 1)	((∘ (∘ v u) v) 1))
  (check-equal? ((∘ v (∘ u v)) 1 2)	((∘ (∘ v u) v) 1 2))
  (check-equal? ((∘ v (∘ u v)) 1 2 3 4)	((∘ (∘ v u) v) 1 2 3 4))
  (check-equal? ((∘ v (∘ u v*)) 1)	((∘ (∘ v u) v*) 1))
  (check-equal? ((∘ v (∘ u v*)) 1 2)	((∘ (∘ v u) v*) 1 2))
  (check-equal? ((∘ v (∘ u v*)) 1 2 3 4)	((∘ (∘ v u) v*) 1 2 3 4))
  (check-equal? ((∘ v (∘ u o)) 1)	((∘ (∘ v u) o) 1))
  (check-equal? ((∘ v (∘ u o)) 1 2)	((∘ (∘ v u) o) 1 2))
  (check-equal? ((∘ v (∘ u o)) 1 2 3 4)	((∘ (∘ v u) o) 1 2 3 4))
  (check-equal? ((∘ v (∘ b n)) 1)	((∘ (∘ v b) n) 1))
  (check-equal? ((∘ v (∘ b n)) 1 2)	((∘ (∘ v b) n) 1 2))
  (check-equal? ((∘ v (∘ b n)) 1 2 3 4)	((∘ (∘ v b) n) 1 2 3 4))
  (check-equal? ((∘ v (∘ b u)) 1 2)	((∘ (∘ v b) u) 1 2))
  (check-equal? ((∘ v (∘ b u)) 1 2 3)	((∘ (∘ v b) u) 1 2 3))
  (check-equal? ((∘ v (∘ b u)) 1 2 3 4 5)	((∘ (∘ v b) u) 1 2 3 4 5))
  (check-equal? ((∘ v (∘ b b)) 1 2 3)	((∘ (∘ v b) b) 1 2 3))
  (check-equal? ((∘ v (∘ b b)) 1 2 3 4)	((∘ (∘ v b) b) 1 2 3 4))
  (check-equal? ((∘ v (∘ b b)) 1 2 3 4 5 6)	((∘ (∘ v b) b) 1 2 3 4 5 6))
  (check-equal? ((∘ v (∘ b t)) 1 2 3 4)	((∘ (∘ v b) t) 1 2 3 4))
  (check-equal? ((∘ v (∘ b t)) 1 2 3 4 5)	((∘ (∘ v b) t) 1 2 3 4 5))
  (check-equal? ((∘ v (∘ b t)) 1 2 3 4 5 6 7)	((∘ (∘ v b) t) 1 2 3 4 5 6 7))
  (check-equal? ((∘ v (∘ b n*)) 1 2)	((∘ (∘ v b) n*) 1 2))
  (check-equal? ((∘ v (∘ b n*)) 1 2 3)	((∘ (∘ v b) n*) 1 2 3))
  (check-equal? ((∘ v (∘ b n*)) 1 2 3 4 5)	((∘ (∘ v b) n*) 1 2 3 4 5))
  (check-equal? ((∘ v (∘ b u*)) 1 2)	((∘ (∘ v b) u*) 1 2))
  (check-equal? ((∘ v (∘ b u*)) 1 2 3)	((∘ (∘ v b) u*) 1 2 3))
  (check-equal? ((∘ v (∘ b u*)) 1 2 3 4 5)	((∘ (∘ v b) u*) 1 2 3 4 5))
  (check-equal? ((∘ v (∘ b b*)) 1 2 3)	((∘ (∘ v b) b*) 1 2 3))
  (check-equal? ((∘ v (∘ b b*)) 1 2 3 4)	((∘ (∘ v b) b*) 1 2 3 4))
  (check-equal? ((∘ v (∘ b b*)) 1 2 3 4 5 6)	((∘ (∘ v b) b*) 1 2 3 4 5 6))
  (check-equal? ((∘ v (∘ b v)) 1 2)	((∘ (∘ v b) v) 1 2))
  (check-equal? ((∘ v (∘ b v)) 1 2 3)	((∘ (∘ v b) v) 1 2 3))
  (check-equal? ((∘ v (∘ b v)) 1 2 3 4 5)	((∘ (∘ v b) v) 1 2 3 4 5))
  (check-equal? ((∘ v (∘ b v*)) 1 2)	((∘ (∘ v b) v*) 1 2))
  (check-equal? ((∘ v (∘ b v*)) 1 2 3)	((∘ (∘ v b) v*) 1 2 3))
  (check-equal? ((∘ v (∘ b v*)) 1 2 3 4 5)	((∘ (∘ v b) v*) 1 2 3 4 5))
  (check-equal? ((∘ v (∘ b o)) 1 2)	((∘ (∘ v b) o) 1 2))
  (check-equal? ((∘ v (∘ b o)) 1 2 3)	((∘ (∘ v b) o) 1 2 3))
  (check-equal? ((∘ v (∘ b o)) 1 2 3 4 5)	((∘ (∘ v b) o) 1 2 3 4 5))
  (check-equal? ((∘ v (∘ t n)) 1 2)	((∘ (∘ v t) n) 1 2))
  (check-equal? ((∘ v (∘ t n)) 1 2 3)	((∘ (∘ v t) n) 1 2 3))
  (check-equal? ((∘ v (∘ t n)) 1 2 3 4 5)	((∘ (∘ v t) n) 1 2 3 4 5))
  (check-equal? ((∘ v (∘ t u)) 1 2 3)	((∘ (∘ v t) u) 1 2 3))
  (check-equal? ((∘ v (∘ t u)) 1 2 3 4)	((∘ (∘ v t) u) 1 2 3 4))
  (check-equal? ((∘ v (∘ t u)) 1 2 3 4 5 6)	((∘ (∘ v t) u) 1 2 3 4 5 6))
  (check-equal? ((∘ v (∘ t b)) 1 2 3 4)	((∘ (∘ v t) b) 1 2 3 4))
  (check-equal? ((∘ v (∘ t b)) 1 2 3 4 5)	((∘ (∘ v t) b) 1 2 3 4 5))
  (check-equal? ((∘ v (∘ t b)) 1 2 3 4 5 6 7)	((∘ (∘ v t) b) 1 2 3 4 5 6 7))
  (check-equal? ((∘ v (∘ t t)) 1 2 3 4 5)	((∘ (∘ v t) t) 1 2 3 4 5))
  (check-equal? ((∘ v (∘ t t)) 1 2 3 4 5 6)	((∘ (∘ v t) t) 1 2 3 4 5 6))
  (check-equal? ((∘ v (∘ t t)) 1 2 3 4 5 6 7 8)	((∘ (∘ v t) t) 1 2 3 4 5 6 7 8))
  (check-equal? ((∘ v (∘ t n*)) 1 2 3)	((∘ (∘ v t) n*) 1 2 3))
  (check-equal? ((∘ v (∘ t n*)) 1 2 3 4)	((∘ (∘ v t) n*) 1 2 3 4))
  (check-equal? ((∘ v (∘ t n*)) 1 2 3 4 5 6)	((∘ (∘ v t) n*) 1 2 3 4 5 6))
  (check-equal? ((∘ v (∘ t u*)) 1 2 3)	((∘ (∘ v t) u*) 1 2 3))
  (check-equal? ((∘ v (∘ t u*)) 1 2 3 4)	((∘ (∘ v t) u*) 1 2 3 4))
  (check-equal? ((∘ v (∘ t u*)) 1 2 3 4 5 6)	((∘ (∘ v t) u*) 1 2 3 4 5 6))
  (check-equal? ((∘ v (∘ t b*)) 1 2 3 4)	((∘ (∘ v t) b*) 1 2 3 4))
  (check-equal? ((∘ v (∘ t b*)) 1 2 3 4 5)	((∘ (∘ v t) b*) 1 2 3 4 5))
  (check-equal? ((∘ v (∘ t b*)) 1 2 3 4 5 6 7)	((∘ (∘ v t) b*) 1 2 3 4 5 6 7))
  (check-equal? ((∘ v (∘ t v)) 1 2 3)	((∘ (∘ v t) v) 1 2 3))
  (check-equal? ((∘ v (∘ t v)) 1 2 3 4)	((∘ (∘ v t) v) 1 2 3 4))
  (check-equal? ((∘ v (∘ t v)) 1 2 3 4 5 6)	((∘ (∘ v t) v) 1 2 3 4 5 6))
  (check-equal? ((∘ v (∘ t v*)) 1 2 3)	((∘ (∘ v t) v*) 1 2 3))
  (check-equal? ((∘ v (∘ t v*)) 1 2 3 4)	((∘ (∘ v t) v*) 1 2 3 4))
  (check-equal? ((∘ v (∘ t v*)) 1 2 3 4 5 6)	((∘ (∘ v t) v*) 1 2 3 4 5 6))
  (check-equal? ((∘ v (∘ t o)) 1 2 3)	((∘ (∘ v t) o) 1 2 3))
  (check-equal? ((∘ v (∘ t o)) 1 2 3 4)	((∘ (∘ v t) o) 1 2 3 4))
  (check-equal? ((∘ v (∘ t o)) 1 2 3 4 5 6)	((∘ (∘ v t) o) 1 2 3 4 5 6))
  (check-equal? ((∘ v (∘ v n)))	((∘ (∘ v v) n)))
  (check-equal? ((∘ v (∘ v n)) 1)	((∘ (∘ v v) n) 1))
  (check-equal? ((∘ v (∘ v n)) 1 2 3)	((∘ (∘ v v) n) 1 2 3))
  (check-equal? ((∘ v (∘ v u)) 1)	((∘ (∘ v v) u) 1))
  (check-equal? ((∘ v (∘ v u)) 1 2)	((∘ (∘ v v) u) 1 2))
  (check-equal? ((∘ v (∘ v u)) 1 2 3 4)	((∘ (∘ v v) u) 1 2 3 4))
  (check-equal? ((∘ v (∘ v b)) 1 2)	((∘ (∘ v v) b) 1 2))
  (check-equal? ((∘ v (∘ v b)) 1 2 3)	((∘ (∘ v v) b) 1 2 3))
  (check-equal? ((∘ v (∘ v b)) 1 2 3 4 5)	((∘ (∘ v v) b) 1 2 3 4 5))
  (check-equal? ((∘ v (∘ v t)) 1 2 3)	((∘ (∘ v v) t) 1 2 3))
  (check-equal? ((∘ v (∘ v t)) 1 2 3 4)	((∘ (∘ v v) t) 1 2 3 4))
  (check-equal? ((∘ v (∘ v t)) 1 2 3 4 5 6)	((∘ (∘ v v) t) 1 2 3 4 5 6))
  (check-equal? ((∘ v (∘ v n*)) 1)	((∘ (∘ v v) n*) 1))
  (check-equal? ((∘ v (∘ v n*)) 1 2)	((∘ (∘ v v) n*) 1 2))
  (check-equal? ((∘ v (∘ v n*)) 1 2 3 4)	((∘ (∘ v v) n*) 1 2 3 4))
  (check-equal? ((∘ v (∘ v u*)) 1)	((∘ (∘ v v) u*) 1))
  (check-equal? ((∘ v (∘ v u*)) 1 2)	((∘ (∘ v v) u*) 1 2))
  (check-equal? ((∘ v (∘ v u*)) 1 2 3 4)	((∘ (∘ v v) u*) 1 2 3 4))
  (check-equal? ((∘ v (∘ v b*)) 1 2)	((∘ (∘ v v) b*) 1 2))
  (check-equal? ((∘ v (∘ v b*)) 1 2 3)	((∘ (∘ v v) b*) 1 2 3))
  (check-equal? ((∘ v (∘ v b*)) 1 2 3 4 5)	((∘ (∘ v v) b*) 1 2 3 4 5))
  (check-equal? ((∘ v (∘ v v)) 1)	((∘ (∘ v v) v) 1))
  (check-equal? ((∘ v (∘ v v)) 1 2)	((∘ (∘ v v) v) 1 2))
  (check-equal? ((∘ v (∘ v v)) 1 2 3 4)	((∘ (∘ v v) v) 1 2 3 4))
  (check-equal? ((∘ v (∘ v v*)) 1)	((∘ (∘ v v) v*) 1))
  (check-equal? ((∘ v (∘ v v*)) 1 2)	((∘ (∘ v v) v*) 1 2))
  (check-equal? ((∘ v (∘ v v*)) 1 2 3 4)	((∘ (∘ v v) v*) 1 2 3 4))
  (check-equal? ((∘ v (∘ v o)) 1)	((∘ (∘ v v) o) 1))
  (check-equal? ((∘ v (∘ v o)) 1 2)	((∘ (∘ v v) o) 1 2))
  (check-equal? ((∘ v (∘ v o)) 1 2 3 4)	((∘ (∘ v v) o) 1 2 3 4))
  (check-equal? ((∘ v (∘ o n)))	((∘ (∘ v o) n)))
  (check-equal? ((∘ v (∘ o n)) 1)	((∘ (∘ v o) n) 1))
  (check-equal? ((∘ v (∘ o n)) 1 2 3)	((∘ (∘ v o) n) 1 2 3))
  (check-equal? ((∘ v (∘ o u)) 1)	((∘ (∘ v o) u) 1))
  (check-equal? ((∘ v (∘ o u)) 1 2)	((∘ (∘ v o) u) 1 2))
  (check-equal? ((∘ v (∘ o u)) 1 2 3 4)	((∘ (∘ v o) u) 1 2 3 4))
  (check-equal? ((∘ v (∘ o b)) 1 2)	((∘ (∘ v o) b) 1 2))
  (check-equal? ((∘ v (∘ o b)) 1 2 3)	((∘ (∘ v o) b) 1 2 3))
  (check-equal? ((∘ v (∘ o b)) 1 2 3 4 5)	((∘ (∘ v o) b) 1 2 3 4 5))
  (check-equal? ((∘ v (∘ o t)) 1 2 3)	((∘ (∘ v o) t) 1 2 3))
  (check-equal? ((∘ v (∘ o t)) 1 2 3 4)	((∘ (∘ v o) t) 1 2 3 4))
  (check-equal? ((∘ v (∘ o t)) 1 2 3 4 5 6)	((∘ (∘ v o) t) 1 2 3 4 5 6))
  (check-equal? ((∘ v (∘ o n*)) 1)	((∘ (∘ v o) n*) 1))
  (check-equal? ((∘ v (∘ o n*)) 1 2)	((∘ (∘ v o) n*) 1 2))
  (check-equal? ((∘ v (∘ o n*)) 1 2 3 4)	((∘ (∘ v o) n*) 1 2 3 4))
  (check-equal? ((∘ v (∘ o u*)) 1)	((∘ (∘ v o) u*) 1))
  (check-equal? ((∘ v (∘ o u*)) 1 2)	((∘ (∘ v o) u*) 1 2))
  (check-equal? ((∘ v (∘ o u*)) 1 2 3 4)	((∘ (∘ v o) u*) 1 2 3 4))
  (check-equal? ((∘ v (∘ o b*)) 1 2)	((∘ (∘ v o) b*) 1 2))
  (check-equal? ((∘ v (∘ o b*)) 1 2 3)	((∘ (∘ v o) b*) 1 2 3))
  (check-equal? ((∘ v (∘ o b*)) 1 2 3 4 5)	((∘ (∘ v o) b*) 1 2 3 4 5))
  (check-equal? ((∘ v (∘ o v)) 1)	((∘ (∘ v o) v) 1))
  (check-equal? ((∘ v (∘ o v)) 1 2)	((∘ (∘ v o) v) 1 2))
  (check-equal? ((∘ v (∘ o v)) 1 2 3 4)	((∘ (∘ v o) v) 1 2 3 4))
  (check-equal? ((∘ v (∘ o v*)) 1)	((∘ (∘ v o) v*) 1))
  (check-equal? ((∘ v (∘ o v*)) 1 2)	((∘ (∘ v o) v*) 1 2))
  (check-equal? ((∘ v (∘ o v*)) 1 2 3 4)	((∘ (∘ v o) v*) 1 2 3 4))
  (check-equal? ((∘ v (∘ o o)) 1)	((∘ (∘ v o) o) 1))
  (check-equal? ((∘ v (∘ o o)) 1 2)	((∘ (∘ v o) o) 1 2))
  (check-equal? ((∘ v (∘ o o)) 1 2 3 4)	((∘ (∘ v o) o) 1 2 3 4))
  (check-equal? ((∘ v* (∘ u n)))	((∘ (∘ v* u) n)))
  (check-equal? ((∘ v* (∘ u n)) 1)	((∘ (∘ v* u) n) 1))
  (check-equal? ((∘ v* (∘ u n)) 1 2)	((∘ (∘ v* u) n) 1 2))
  (check-equal? ((∘ v* (∘ u n)) 1 2 3)	((∘ (∘ v* u) n) 1 2 3))
  (check-equal? ((∘ v* (∘ u u)) 1)	((∘ (∘ v* u) u) 1))
  (check-equal? ((∘ v* (∘ u u)) 1 2)	((∘ (∘ v* u) u) 1 2))
  (check-equal? ((∘ v* (∘ u u)) 1 2 3)	((∘ (∘ v* u) u) 1 2 3))
  (check-equal? ((∘ v* (∘ u u)) 1 2 3 4)	((∘ (∘ v* u) u) 1 2 3 4))
  (check-equal? ((∘ v* (∘ u b)) 1 2)	((∘ (∘ v* u) b) 1 2))
  (check-equal? ((∘ v* (∘ u b)) 1 2 3)	((∘ (∘ v* u) b) 1 2 3))
  (check-equal? ((∘ v* (∘ u b)) 1 2 3 4)	((∘ (∘ v* u) b) 1 2 3 4))
  (check-equal? ((∘ v* (∘ u b)) 1 2 3 4 5)	((∘ (∘ v* u) b) 1 2 3 4 5))
  (check-equal? ((∘ v* (∘ u t)) 1 2 3)	((∘ (∘ v* u) t) 1 2 3))
  (check-equal? ((∘ v* (∘ u t)) 1 2 3 4)	((∘ (∘ v* u) t) 1 2 3 4))
  (check-equal? ((∘ v* (∘ u t)) 1 2 3 4 5)	((∘ (∘ v* u) t) 1 2 3 4 5))
  (check-equal? ((∘ v* (∘ u t)) 1 2 3 4 5 6)	((∘ (∘ v* u) t) 1 2 3 4 5 6))
  (check-equal? ((∘ v* (∘ u n*)) 1)	((∘ (∘ v* u) n*) 1))
  (check-equal? ((∘ v* (∘ u n*)) 1 2)	((∘ (∘ v* u) n*) 1 2))
  (check-equal? ((∘ v* (∘ u n*)) 1 2 3)	((∘ (∘ v* u) n*) 1 2 3))
  (check-equal? ((∘ v* (∘ u n*)) 1 2 3 4)	((∘ (∘ v* u) n*) 1 2 3 4))
  (check-equal? ((∘ v* (∘ u u*)) 1)	((∘ (∘ v* u) u*) 1))
  (check-equal? ((∘ v* (∘ u u*)) 1 2)	((∘ (∘ v* u) u*) 1 2))
  (check-equal? ((∘ v* (∘ u u*)) 1 2 3)	((∘ (∘ v* u) u*) 1 2 3))
  (check-equal? ((∘ v* (∘ u u*)) 1 2 3 4)	((∘ (∘ v* u) u*) 1 2 3 4))
  (check-equal? ((∘ v* (∘ u b*)) 1 2)	((∘ (∘ v* u) b*) 1 2))
  (check-equal? ((∘ v* (∘ u b*)) 1 2 3)	((∘ (∘ v* u) b*) 1 2 3))
  (check-equal? ((∘ v* (∘ u b*)) 1 2 3 4)	((∘ (∘ v* u) b*) 1 2 3 4))
  (check-equal? ((∘ v* (∘ u b*)) 1 2 3 4 5)	((∘ (∘ v* u) b*) 1 2 3 4 5))
  (check-equal? ((∘ v* (∘ u v)) 1)	((∘ (∘ v* u) v) 1))
  (check-equal? ((∘ v* (∘ u v)) 1 2)	((∘ (∘ v* u) v) 1 2))
  (check-equal? ((∘ v* (∘ u v)) 1 2 3)	((∘ (∘ v* u) v) 1 2 3))
  (check-equal? ((∘ v* (∘ u v)) 1 2 3 4)	((∘ (∘ v* u) v) 1 2 3 4))
  (check-equal? ((∘ v* (∘ u v*)) 1)	((∘ (∘ v* u) v*) 1))
  (check-equal? ((∘ v* (∘ u v*)) 1 2)	((∘ (∘ v* u) v*) 1 2))
  (check-equal? ((∘ v* (∘ u v*)) 1 2 3)	((∘ (∘ v* u) v*) 1 2 3))
  (check-equal? ((∘ v* (∘ u v*)) 1 2 3 4)	((∘ (∘ v* u) v*) 1 2 3 4))
  (check-equal? ((∘ v* (∘ u o)) 1)	((∘ (∘ v* u) o) 1))
  (check-equal? ((∘ v* (∘ u o)) 1 2)	((∘ (∘ v* u) o) 1 2))
  (check-equal? ((∘ v* (∘ u o)) 1 2 3)	((∘ (∘ v* u) o) 1 2 3))
  (check-equal? ((∘ v* (∘ u o)) 1 2 3 4)	((∘ (∘ v* u) o) 1 2 3 4))
  (check-equal? ((∘ v* (∘ b n)) 1)	((∘ (∘ v* b) n) 1))
  (check-equal? ((∘ v* (∘ b n)) 1 2)	((∘ (∘ v* b) n) 1 2))
  (check-equal? ((∘ v* (∘ b n)) 1 2 3)	((∘ (∘ v* b) n) 1 2 3))
  (check-equal? ((∘ v* (∘ b n)) 1 2 3 4)	((∘ (∘ v* b) n) 1 2 3 4))
  (check-equal? ((∘ v* (∘ b u)) 1 2)	((∘ (∘ v* b) u) 1 2))
  (check-equal? ((∘ v* (∘ b u)) 1 2 3)	((∘ (∘ v* b) u) 1 2 3))
  (check-equal? ((∘ v* (∘ b u)) 1 2 3 4)	((∘ (∘ v* b) u) 1 2 3 4))
  (check-equal? ((∘ v* (∘ b u)) 1 2 3 4 5)	((∘ (∘ v* b) u) 1 2 3 4 5))
  (check-equal? ((∘ v* (∘ b b)) 1 2 3)	((∘ (∘ v* b) b) 1 2 3))
  (check-equal? ((∘ v* (∘ b b)) 1 2 3 4)	((∘ (∘ v* b) b) 1 2 3 4))
  (check-equal? ((∘ v* (∘ b b)) 1 2 3 4 5)	((∘ (∘ v* b) b) 1 2 3 4 5))
  (check-equal? ((∘ v* (∘ b b)) 1 2 3 4 5 6)	((∘ (∘ v* b) b) 1 2 3 4 5 6))
  (check-equal? ((∘ v* (∘ b t)) 1 2 3 4)	((∘ (∘ v* b) t) 1 2 3 4))
  (check-equal? ((∘ v* (∘ b t)) 1 2 3 4 5)	((∘ (∘ v* b) t) 1 2 3 4 5))
  (check-equal? ((∘ v* (∘ b t)) 1 2 3 4 5 6)	((∘ (∘ v* b) t) 1 2 3 4 5 6))
  (check-equal? ((∘ v* (∘ b t)) 1 2 3 4 5 6 7)	((∘ (∘ v* b) t) 1 2 3 4 5 6 7))
  (check-equal? ((∘ v* (∘ b n*)) 1 2)	((∘ (∘ v* b) n*) 1 2))
  (check-equal? ((∘ v* (∘ b n*)) 1 2 3)	((∘ (∘ v* b) n*) 1 2 3))
  (check-equal? ((∘ v* (∘ b n*)) 1 2 3 4)	((∘ (∘ v* b) n*) 1 2 3 4))
  (check-equal? ((∘ v* (∘ b n*)) 1 2 3 4 5)	((∘ (∘ v* b) n*) 1 2 3 4 5))
  (check-equal? ((∘ v* (∘ b u*)) 1 2)	((∘ (∘ v* b) u*) 1 2))
  (check-equal? ((∘ v* (∘ b u*)) 1 2 3)	((∘ (∘ v* b) u*) 1 2 3))
  (check-equal? ((∘ v* (∘ b u*)) 1 2 3 4)	((∘ (∘ v* b) u*) 1 2 3 4))
  (check-equal? ((∘ v* (∘ b u*)) 1 2 3 4 5)	((∘ (∘ v* b) u*) 1 2 3 4 5))
  (check-equal? ((∘ v* (∘ b b*)) 1 2 3)	((∘ (∘ v* b) b*) 1 2 3))
  (check-equal? ((∘ v* (∘ b b*)) 1 2 3 4)	((∘ (∘ v* b) b*) 1 2 3 4))
  (check-equal? ((∘ v* (∘ b b*)) 1 2 3 4 5)	((∘ (∘ v* b) b*) 1 2 3 4 5))
  (check-equal? ((∘ v* (∘ b b*)) 1 2 3 4 5 6)	((∘ (∘ v* b) b*) 1 2 3 4 5 6))
  (check-equal? ((∘ v* (∘ b v)) 1 2)	((∘ (∘ v* b) v) 1 2))
  (check-equal? ((∘ v* (∘ b v)) 1 2 3)	((∘ (∘ v* b) v) 1 2 3))
  (check-equal? ((∘ v* (∘ b v)) 1 2 3 4)	((∘ (∘ v* b) v) 1 2 3 4))
  (check-equal? ((∘ v* (∘ b v)) 1 2 3 4 5)	((∘ (∘ v* b) v) 1 2 3 4 5))
  (check-equal? ((∘ v* (∘ b v*)) 1 2)	((∘ (∘ v* b) v*) 1 2))
  (check-equal? ((∘ v* (∘ b v*)) 1 2 3)	((∘ (∘ v* b) v*) 1 2 3))
  (check-equal? ((∘ v* (∘ b v*)) 1 2 3 4)	((∘ (∘ v* b) v*) 1 2 3 4))
  (check-equal? ((∘ v* (∘ b v*)) 1 2 3 4 5)	((∘ (∘ v* b) v*) 1 2 3 4 5))
  (check-equal? ((∘ v* (∘ b o)) 1 2)	((∘ (∘ v* b) o) 1 2))
  (check-equal? ((∘ v* (∘ b o)) 1 2 3)	((∘ (∘ v* b) o) 1 2 3))
  (check-equal? ((∘ v* (∘ b o)) 1 2 3 4)	((∘ (∘ v* b) o) 1 2 3 4))
  (check-equal? ((∘ v* (∘ b o)) 1 2 3 4 5)	((∘ (∘ v* b) o) 1 2 3 4 5))
  (check-equal? ((∘ v* (∘ t n)) 1 2)	((∘ (∘ v* t) n) 1 2))
  (check-equal? ((∘ v* (∘ t n)) 1 2 3)	((∘ (∘ v* t) n) 1 2 3))
  (check-equal? ((∘ v* (∘ t n)) 1 2 3 4)	((∘ (∘ v* t) n) 1 2 3 4))
  (check-equal? ((∘ v* (∘ t n)) 1 2 3 4 5)	((∘ (∘ v* t) n) 1 2 3 4 5))
  (check-equal? ((∘ v* (∘ t u)) 1 2 3)	((∘ (∘ v* t) u) 1 2 3))
  (check-equal? ((∘ v* (∘ t u)) 1 2 3 4)	((∘ (∘ v* t) u) 1 2 3 4))
  (check-equal? ((∘ v* (∘ t u)) 1 2 3 4 5)	((∘ (∘ v* t) u) 1 2 3 4 5))
  (check-equal? ((∘ v* (∘ t u)) 1 2 3 4 5 6)	((∘ (∘ v* t) u) 1 2 3 4 5 6))
  (check-equal? ((∘ v* (∘ t b)) 1 2 3 4)	((∘ (∘ v* t) b) 1 2 3 4))
  (check-equal? ((∘ v* (∘ t b)) 1 2 3 4 5)	((∘ (∘ v* t) b) 1 2 3 4 5))
  (check-equal? ((∘ v* (∘ t b)) 1 2 3 4 5 6)	((∘ (∘ v* t) b) 1 2 3 4 5 6))
  (check-equal? ((∘ v* (∘ t b)) 1 2 3 4 5 6 7)	((∘ (∘ v* t) b) 1 2 3 4 5 6 7))
  (check-equal? ((∘ v* (∘ t t)) 1 2 3 4 5)	((∘ (∘ v* t) t) 1 2 3 4 5))
  (check-equal? ((∘ v* (∘ t t)) 1 2 3 4 5 6)	((∘ (∘ v* t) t) 1 2 3 4 5 6))
  (check-equal? ((∘ v* (∘ t t)) 1 2 3 4 5 6 7)	((∘ (∘ v* t) t) 1 2 3 4 5 6 7))
  (check-equal? ((∘ v* (∘ t t)) 1 2 3 4 5 6 7 8)	((∘ (∘ v* t) t) 1 2 3 4 5 6 7 8))
  (check-equal? ((∘ v* (∘ t n*)) 1 2 3)	((∘ (∘ v* t) n*) 1 2 3))
  (check-equal? ((∘ v* (∘ t n*)) 1 2 3 4)	((∘ (∘ v* t) n*) 1 2 3 4))
  (check-equal? ((∘ v* (∘ t n*)) 1 2 3 4 5)	((∘ (∘ v* t) n*) 1 2 3 4 5))
  (check-equal? ((∘ v* (∘ t n*)) 1 2 3 4 5 6)	((∘ (∘ v* t) n*) 1 2 3 4 5 6))
  (check-equal? ((∘ v* (∘ t u*)) 1 2 3)	((∘ (∘ v* t) u*) 1 2 3))
  (check-equal? ((∘ v* (∘ t u*)) 1 2 3 4)	((∘ (∘ v* t) u*) 1 2 3 4))
  (check-equal? ((∘ v* (∘ t u*)) 1 2 3 4 5)	((∘ (∘ v* t) u*) 1 2 3 4 5))
  (check-equal? ((∘ v* (∘ t u*)) 1 2 3 4 5 6)	((∘ (∘ v* t) u*) 1 2 3 4 5 6))
  (check-equal? ((∘ v* (∘ t b*)) 1 2 3 4)	((∘ (∘ v* t) b*) 1 2 3 4))
  (check-equal? ((∘ v* (∘ t b*)) 1 2 3 4 5)	((∘ (∘ v* t) b*) 1 2 3 4 5))
  (check-equal? ((∘ v* (∘ t b*)) 1 2 3 4 5 6)	((∘ (∘ v* t) b*) 1 2 3 4 5 6))
  (check-equal? ((∘ v* (∘ t b*)) 1 2 3 4 5 6 7)	((∘ (∘ v* t) b*) 1 2 3 4 5 6 7))
  (check-equal? ((∘ v* (∘ t v)) 1 2 3)	((∘ (∘ v* t) v) 1 2 3))
  (check-equal? ((∘ v* (∘ t v)) 1 2 3 4)	((∘ (∘ v* t) v) 1 2 3 4))
  (check-equal? ((∘ v* (∘ t v)) 1 2 3 4 5)	((∘ (∘ v* t) v) 1 2 3 4 5))
  (check-equal? ((∘ v* (∘ t v)) 1 2 3 4 5 6)	((∘ (∘ v* t) v) 1 2 3 4 5 6))
  (check-equal? ((∘ v* (∘ t v*)) 1 2 3)	((∘ (∘ v* t) v*) 1 2 3))
  (check-equal? ((∘ v* (∘ t v*)) 1 2 3 4)	((∘ (∘ v* t) v*) 1 2 3 4))
  (check-equal? ((∘ v* (∘ t v*)) 1 2 3 4 5)	((∘ (∘ v* t) v*) 1 2 3 4 5))
  (check-equal? ((∘ v* (∘ t v*)) 1 2 3 4 5 6)	((∘ (∘ v* t) v*) 1 2 3 4 5 6))
  (check-equal? ((∘ v* (∘ t o)) 1 2 3)	((∘ (∘ v* t) o) 1 2 3))
  (check-equal? ((∘ v* (∘ t o)) 1 2 3 4)	((∘ (∘ v* t) o) 1 2 3 4))
  (check-equal? ((∘ v* (∘ t o)) 1 2 3 4 5)	((∘ (∘ v* t) o) 1 2 3 4 5))
  (check-equal? ((∘ v* (∘ t o)) 1 2 3 4 5 6)	((∘ (∘ v* t) o) 1 2 3 4 5 6))
  (check-equal? ((∘ v* (∘ v n)))	((∘ (∘ v* v) n)))
  (check-equal? ((∘ v* (∘ v n)) 1)	((∘ (∘ v* v) n) 1))
  (check-equal? ((∘ v* (∘ v n)) 1 2)	((∘ (∘ v* v) n) 1 2))
  (check-equal? ((∘ v* (∘ v n)) 1 2 3)	((∘ (∘ v* v) n) 1 2 3))
  (check-equal? ((∘ v* (∘ v u)) 1)	((∘ (∘ v* v) u) 1))
  (check-equal? ((∘ v* (∘ v u)) 1 2)	((∘ (∘ v* v) u) 1 2))
  (check-equal? ((∘ v* (∘ v u)) 1 2 3)	((∘ (∘ v* v) u) 1 2 3))
  (check-equal? ((∘ v* (∘ v u)) 1 2 3 4)	((∘ (∘ v* v) u) 1 2 3 4))
  (check-equal? ((∘ v* (∘ v b)) 1 2)	((∘ (∘ v* v) b) 1 2))
  (check-equal? ((∘ v* (∘ v b)) 1 2 3)	((∘ (∘ v* v) b) 1 2 3))
  (check-equal? ((∘ v* (∘ v b)) 1 2 3 4)	((∘ (∘ v* v) b) 1 2 3 4))
  (check-equal? ((∘ v* (∘ v b)) 1 2 3 4 5)	((∘ (∘ v* v) b) 1 2 3 4 5))
  (check-equal? ((∘ v* (∘ v t)) 1 2 3)	((∘ (∘ v* v) t) 1 2 3))
  (check-equal? ((∘ v* (∘ v t)) 1 2 3 4)	((∘ (∘ v* v) t) 1 2 3 4))
  (check-equal? ((∘ v* (∘ v t)) 1 2 3 4 5)	((∘ (∘ v* v) t) 1 2 3 4 5))
  (check-equal? ((∘ v* (∘ v t)) 1 2 3 4 5 6)	((∘ (∘ v* v) t) 1 2 3 4 5 6))
  (check-equal? ((∘ v* (∘ v n*)) 1)	((∘ (∘ v* v) n*) 1))
  (check-equal? ((∘ v* (∘ v n*)) 1 2)	((∘ (∘ v* v) n*) 1 2))
  (check-equal? ((∘ v* (∘ v n*)) 1 2 3)	((∘ (∘ v* v) n*) 1 2 3))
  (check-equal? ((∘ v* (∘ v n*)) 1 2 3 4)	((∘ (∘ v* v) n*) 1 2 3 4))
  (check-equal? ((∘ v* (∘ v u*)) 1)	((∘ (∘ v* v) u*) 1))
  (check-equal? ((∘ v* (∘ v u*)) 1 2)	((∘ (∘ v* v) u*) 1 2))
  (check-equal? ((∘ v* (∘ v u*)) 1 2 3)	((∘ (∘ v* v) u*) 1 2 3))
  (check-equal? ((∘ v* (∘ v u*)) 1 2 3 4)	((∘ (∘ v* v) u*) 1 2 3 4))
  (check-equal? ((∘ v* (∘ v b*)) 1 2)	((∘ (∘ v* v) b*) 1 2))
  (check-equal? ((∘ v* (∘ v b*)) 1 2 3)	((∘ (∘ v* v) b*) 1 2 3))
  (check-equal? ((∘ v* (∘ v b*)) 1 2 3 4)	((∘ (∘ v* v) b*) 1 2 3 4))
  (check-equal? ((∘ v* (∘ v b*)) 1 2 3 4 5)	((∘ (∘ v* v) b*) 1 2 3 4 5))
  (check-equal? ((∘ v* (∘ v v)) 1)	((∘ (∘ v* v) v) 1))
  (check-equal? ((∘ v* (∘ v v)) 1 2)	((∘ (∘ v* v) v) 1 2))
  (check-equal? ((∘ v* (∘ v v)) 1 2 3)	((∘ (∘ v* v) v) 1 2 3))
  (check-equal? ((∘ v* (∘ v v)) 1 2 3 4)	((∘ (∘ v* v) v) 1 2 3 4))
  (check-equal? ((∘ v* (∘ v v*)) 1)	((∘ (∘ v* v) v*) 1))
  (check-equal? ((∘ v* (∘ v v*)) 1 2)	((∘ (∘ v* v) v*) 1 2))
  (check-equal? ((∘ v* (∘ v v*)) 1 2 3)	((∘ (∘ v* v) v*) 1 2 3))
  (check-equal? ((∘ v* (∘ v v*)) 1 2 3 4)	((∘ (∘ v* v) v*) 1 2 3 4))
  (check-equal? ((∘ v* (∘ v o)) 1)	((∘ (∘ v* v) o) 1))
  (check-equal? ((∘ v* (∘ v o)) 1 2)	((∘ (∘ v* v) o) 1 2))
  (check-equal? ((∘ v* (∘ v o)) 1 2 3)	((∘ (∘ v* v) o) 1 2 3))
  (check-equal? ((∘ v* (∘ v o)) 1 2 3 4)	((∘ (∘ v* v) o) 1 2 3 4))
  (check-equal? ((∘ v* (∘ o n)))	((∘ (∘ v* o) n)))
  (check-equal? ((∘ v* (∘ o n)) 1)	((∘ (∘ v* o) n) 1))
  (check-equal? ((∘ v* (∘ o n)) 1 2)	((∘ (∘ v* o) n) 1 2))
  (check-equal? ((∘ v* (∘ o n)) 1 2 3)	((∘ (∘ v* o) n) 1 2 3))
  (check-equal? ((∘ v* (∘ o u)) 1)	((∘ (∘ v* o) u) 1))
  (check-equal? ((∘ v* (∘ o u)) 1 2)	((∘ (∘ v* o) u) 1 2))
  (check-equal? ((∘ v* (∘ o u)) 1 2 3)	((∘ (∘ v* o) u) 1 2 3))
  (check-equal? ((∘ v* (∘ o u)) 1 2 3 4)	((∘ (∘ v* o) u) 1 2 3 4))
  (check-equal? ((∘ v* (∘ o b)) 1 2)	((∘ (∘ v* o) b) 1 2))
  (check-equal? ((∘ v* (∘ o b)) 1 2 3)	((∘ (∘ v* o) b) 1 2 3))
  (check-equal? ((∘ v* (∘ o b)) 1 2 3 4)	((∘ (∘ v* o) b) 1 2 3 4))
  (check-equal? ((∘ v* (∘ o b)) 1 2 3 4 5)	((∘ (∘ v* o) b) 1 2 3 4 5))
  (check-equal? ((∘ v* (∘ o t)) 1 2 3)	((∘ (∘ v* o) t) 1 2 3))
  (check-equal? ((∘ v* (∘ o t)) 1 2 3 4)	((∘ (∘ v* o) t) 1 2 3 4))
  (check-equal? ((∘ v* (∘ o t)) 1 2 3 4 5)	((∘ (∘ v* o) t) 1 2 3 4 5))
  (check-equal? ((∘ v* (∘ o t)) 1 2 3 4 5 6)	((∘ (∘ v* o) t) 1 2 3 4 5 6))
  (check-equal? ((∘ v* (∘ o n*)) 1)	((∘ (∘ v* o) n*) 1))
  (check-equal? ((∘ v* (∘ o n*)) 1 2)	((∘ (∘ v* o) n*) 1 2))
  (check-equal? ((∘ v* (∘ o n*)) 1 2 3)	((∘ (∘ v* o) n*) 1 2 3))
  (check-equal? ((∘ v* (∘ o n*)) 1 2 3 4)	((∘ (∘ v* o) n*) 1 2 3 4))
  (check-equal? ((∘ v* (∘ o u*)) 1)	((∘ (∘ v* o) u*) 1))
  (check-equal? ((∘ v* (∘ o u*)) 1 2)	((∘ (∘ v* o) u*) 1 2))
  (check-equal? ((∘ v* (∘ o u*)) 1 2 3)	((∘ (∘ v* o) u*) 1 2 3))
  (check-equal? ((∘ v* (∘ o u*)) 1 2 3 4)	((∘ (∘ v* o) u*) 1 2 3 4))
  (check-equal? ((∘ v* (∘ o b*)) 1 2)	((∘ (∘ v* o) b*) 1 2))
  (check-equal? ((∘ v* (∘ o b*)) 1 2 3)	((∘ (∘ v* o) b*) 1 2 3))
  (check-equal? ((∘ v* (∘ o b*)) 1 2 3 4)	((∘ (∘ v* o) b*) 1 2 3 4))
  (check-equal? ((∘ v* (∘ o b*)) 1 2 3 4 5)	((∘ (∘ v* o) b*) 1 2 3 4 5))
  (check-equal? ((∘ v* (∘ o v)) 1)	((∘ (∘ v* o) v) 1))
  (check-equal? ((∘ v* (∘ o v)) 1 2)	((∘ (∘ v* o) v) 1 2))
  (check-equal? ((∘ v* (∘ o v)) 1 2 3)	((∘ (∘ v* o) v) 1 2 3))
  (check-equal? ((∘ v* (∘ o v)) 1 2 3 4)	((∘ (∘ v* o) v) 1 2 3 4))
  (check-equal? ((∘ v* (∘ o v*)) 1)	((∘ (∘ v* o) v*) 1))
  (check-equal? ((∘ v* (∘ o v*)) 1 2)	((∘ (∘ v* o) v*) 1 2))
  (check-equal? ((∘ v* (∘ o v*)) 1 2 3)	((∘ (∘ v* o) v*) 1 2 3))
  (check-equal? ((∘ v* (∘ o v*)) 1 2 3 4)	((∘ (∘ v* o) v*) 1 2 3 4))
  (check-equal? ((∘ v* (∘ o o)) 1)	((∘ (∘ v* o) o) 1))
  (check-equal? ((∘ v* (∘ o o)) 1 2)	((∘ (∘ v* o) o) 1 2))
  (check-equal? ((∘ v* (∘ o o)) 1 2 3)	((∘ (∘ v* o) o) 1 2 3))
  (check-equal? ((∘ v* (∘ o o)) 1 2 3 4)	((∘ (∘ v* o) o) 1 2 3 4))
  (check-equal? ((∘ o (∘ u n)))	((∘ (∘ o u) n)))
  (check-equal? ((∘ o (∘ u n)) 1)	((∘ (∘ o u) n) 1))
  (check-equal? ((∘ o (∘ u u)) 1)	((∘ (∘ o u) u) 1))
  (check-equal? ((∘ o (∘ u u)) 1 2)	((∘ (∘ o u) u) 1 2))
  (check-equal? ((∘ o (∘ u b)) 1 2)	((∘ (∘ o u) b) 1 2))
  (check-equal? ((∘ o (∘ u b)) 1 2 3)	((∘ (∘ o u) b) 1 2 3))
  (check-equal? ((∘ o (∘ u t)) 1 2 3)	((∘ (∘ o u) t) 1 2 3))
  (check-equal? ((∘ o (∘ u t)) 1 2 3 4)	((∘ (∘ o u) t) 1 2 3 4))
  (check-equal? ((∘ o (∘ u n*)) 1)	((∘ (∘ o u) n*) 1))
  (check-equal? ((∘ o (∘ u n*)) 1 2)	((∘ (∘ o u) n*) 1 2))
  (check-equal? ((∘ o (∘ u u*)) 1)	((∘ (∘ o u) u*) 1))
  (check-equal? ((∘ o (∘ u u*)) 1 2)	((∘ (∘ o u) u*) 1 2))
  (check-equal? ((∘ o (∘ u b*)) 1 2)	((∘ (∘ o u) b*) 1 2))
  (check-equal? ((∘ o (∘ u b*)) 1 2 3)	((∘ (∘ o u) b*) 1 2 3))
  (check-equal? ((∘ o (∘ u v)) 1)	((∘ (∘ o u) v) 1))
  (check-equal? ((∘ o (∘ u v)) 1 2)	((∘ (∘ o u) v) 1 2))
  (check-equal? ((∘ o (∘ u v*)) 1)	((∘ (∘ o u) v*) 1))
  (check-equal? ((∘ o (∘ u v*)) 1 2)	((∘ (∘ o u) v*) 1 2))
  (check-equal? ((∘ o (∘ u o)) 1)	((∘ (∘ o u) o) 1))
  (check-equal? ((∘ o (∘ u o)) 1 2)	((∘ (∘ o u) o) 1 2))
  (check-equal? ((∘ o (∘ b n)) 1)	((∘ (∘ o b) n) 1))
  (check-equal? ((∘ o (∘ b n)) 1 2)	((∘ (∘ o b) n) 1 2))
  (check-equal? ((∘ o (∘ b u)) 1 2)	((∘ (∘ o b) u) 1 2))
  (check-equal? ((∘ o (∘ b u)) 1 2 3)	((∘ (∘ o b) u) 1 2 3))
  (check-equal? ((∘ o (∘ b b)) 1 2 3)	((∘ (∘ o b) b) 1 2 3))
  (check-equal? ((∘ o (∘ b b)) 1 2 3 4)	((∘ (∘ o b) b) 1 2 3 4))
  (check-equal? ((∘ o (∘ b t)) 1 2 3 4)	((∘ (∘ o b) t) 1 2 3 4))
  (check-equal? ((∘ o (∘ b t)) 1 2 3 4 5)	((∘ (∘ o b) t) 1 2 3 4 5))
  (check-equal? ((∘ o (∘ b n*)) 1 2)	((∘ (∘ o b) n*) 1 2))
  (check-equal? ((∘ o (∘ b n*)) 1 2 3)	((∘ (∘ o b) n*) 1 2 3))
  (check-equal? ((∘ o (∘ b u*)) 1 2)	((∘ (∘ o b) u*) 1 2))
  (check-equal? ((∘ o (∘ b u*)) 1 2 3)	((∘ (∘ o b) u*) 1 2 3))
  (check-equal? ((∘ o (∘ b b*)) 1 2 3)	((∘ (∘ o b) b*) 1 2 3))
  (check-equal? ((∘ o (∘ b b*)) 1 2 3 4)	((∘ (∘ o b) b*) 1 2 3 4))
  (check-equal? ((∘ o (∘ b v)) 1 2)	((∘ (∘ o b) v) 1 2))
  (check-equal? ((∘ o (∘ b v)) 1 2 3)	((∘ (∘ o b) v) 1 2 3))
  (check-equal? ((∘ o (∘ b v*)) 1 2)	((∘ (∘ o b) v*) 1 2))
  (check-equal? ((∘ o (∘ b v*)) 1 2 3)	((∘ (∘ o b) v*) 1 2 3))
  (check-equal? ((∘ o (∘ b o)) 1 2)	((∘ (∘ o b) o) 1 2))
  (check-equal? ((∘ o (∘ b o)) 1 2 3)	((∘ (∘ o b) o) 1 2 3))
  (check-equal? ((∘ o (∘ t n)) 1 2)	((∘ (∘ o t) n) 1 2))
  (check-equal? ((∘ o (∘ t n)) 1 2 3)	((∘ (∘ o t) n) 1 2 3))
  (check-equal? ((∘ o (∘ t u)) 1 2 3)	((∘ (∘ o t) u) 1 2 3))
  (check-equal? ((∘ o (∘ t u)) 1 2 3 4)	((∘ (∘ o t) u) 1 2 3 4))
  (check-equal? ((∘ o (∘ t b)) 1 2 3 4)	((∘ (∘ o t) b) 1 2 3 4))
  (check-equal? ((∘ o (∘ t b)) 1 2 3 4 5)	((∘ (∘ o t) b) 1 2 3 4 5))
  (check-equal? ((∘ o (∘ t t)) 1 2 3 4 5)	((∘ (∘ o t) t) 1 2 3 4 5))
  (check-equal? ((∘ o (∘ t t)) 1 2 3 4 5 6)	((∘ (∘ o t) t) 1 2 3 4 5 6))
  (check-equal? ((∘ o (∘ t n*)) 1 2 3)	((∘ (∘ o t) n*) 1 2 3))
  (check-equal? ((∘ o (∘ t n*)) 1 2 3 4)	((∘ (∘ o t) n*) 1 2 3 4))
  (check-equal? ((∘ o (∘ t u*)) 1 2 3)	((∘ (∘ o t) u*) 1 2 3))
  (check-equal? ((∘ o (∘ t u*)) 1 2 3 4)	((∘ (∘ o t) u*) 1 2 3 4))
  (check-equal? ((∘ o (∘ t b*)) 1 2 3 4)	((∘ (∘ o t) b*) 1 2 3 4))
  (check-equal? ((∘ o (∘ t b*)) 1 2 3 4 5)	((∘ (∘ o t) b*) 1 2 3 4 5))
  (check-equal? ((∘ o (∘ t v)) 1 2 3)	((∘ (∘ o t) v) 1 2 3))
  (check-equal? ((∘ o (∘ t v)) 1 2 3 4)	((∘ (∘ o t) v) 1 2 3 4))
  (check-equal? ((∘ o (∘ t v*)) 1 2 3)	((∘ (∘ o t) v*) 1 2 3))
  (check-equal? ((∘ o (∘ t v*)) 1 2 3 4)	((∘ (∘ o t) v*) 1 2 3 4))
  (check-equal? ((∘ o (∘ t o)) 1 2 3)	((∘ (∘ o t) o) 1 2 3))
  (check-equal? ((∘ o (∘ t o)) 1 2 3 4)	((∘ (∘ o t) o) 1 2 3 4))
  (check-equal? ((∘ o (∘ v n)))	((∘ (∘ o v) n)))
  (check-equal? ((∘ o (∘ v n)) 1)	((∘ (∘ o v) n) 1))
  (check-equal? ((∘ o (∘ v u)) 1)	((∘ (∘ o v) u) 1))
  (check-equal? ((∘ o (∘ v u)) 1 2)	((∘ (∘ o v) u) 1 2))
  (check-equal? ((∘ o (∘ v b)) 1 2)	((∘ (∘ o v) b) 1 2))
  (check-equal? ((∘ o (∘ v b)) 1 2 3)	((∘ (∘ o v) b) 1 2 3))
  (check-equal? ((∘ o (∘ v t)) 1 2 3)	((∘ (∘ o v) t) 1 2 3))
  (check-equal? ((∘ o (∘ v t)) 1 2 3 4)	((∘ (∘ o v) t) 1 2 3 4))
  (check-equal? ((∘ o (∘ v n*)) 1)	((∘ (∘ o v) n*) 1))
  (check-equal? ((∘ o (∘ v n*)) 1 2)	((∘ (∘ o v) n*) 1 2))
  (check-equal? ((∘ o (∘ v u*)) 1)	((∘ (∘ o v) u*) 1))
  (check-equal? ((∘ o (∘ v u*)) 1 2)	((∘ (∘ o v) u*) 1 2))
  (check-equal? ((∘ o (∘ v b*)) 1 2)	((∘ (∘ o v) b*) 1 2))
  (check-equal? ((∘ o (∘ v b*)) 1 2 3)	((∘ (∘ o v) b*) 1 2 3))
  (check-equal? ((∘ o (∘ v v)) 1)	((∘ (∘ o v) v) 1))
  (check-equal? ((∘ o (∘ v v)) 1 2)	((∘ (∘ o v) v) 1 2))
  (check-equal? ((∘ o (∘ v v*)) 1)	((∘ (∘ o v) v*) 1))
  (check-equal? ((∘ o (∘ v v*)) 1 2)	((∘ (∘ o v) v*) 1 2))
  (check-equal? ((∘ o (∘ v o)) 1)	((∘ (∘ o v) o) 1))
  (check-equal? ((∘ o (∘ v o)) 1 2)	((∘ (∘ o v) o) 1 2))
  (check-equal? ((∘ o (∘ o n)))	((∘ (∘ o o) n)))
  (check-equal? ((∘ o (∘ o n)) 1)	((∘ (∘ o o) n) 1))
  (check-equal? ((∘ o (∘ o u)) 1)	((∘ (∘ o o) u) 1))
  (check-equal? ((∘ o (∘ o u)) 1 2)	((∘ (∘ o o) u) 1 2))
  (check-equal? ((∘ o (∘ o b)) 1 2)	((∘ (∘ o o) b) 1 2))
  (check-equal? ((∘ o (∘ o b)) 1 2 3)	((∘ (∘ o o) b) 1 2 3))
  (check-equal? ((∘ o (∘ o t)) 1 2 3)	((∘ (∘ o o) t) 1 2 3))
  (check-equal? ((∘ o (∘ o t)) 1 2 3 4)	((∘ (∘ o o) t) 1 2 3 4))
  (check-equal? ((∘ o (∘ o n*)) 1)	((∘ (∘ o o) n*) 1))
  (check-equal? ((∘ o (∘ o n*)) 1 2)	((∘ (∘ o o) n*) 1 2))
  (check-equal? ((∘ o (∘ o u*)) 1)	((∘ (∘ o o) u*) 1))
  (check-equal? ((∘ o (∘ o u*)) 1 2)	((∘ (∘ o o) u*) 1 2))
  (check-equal? ((∘ o (∘ o b*)) 1 2)	((∘ (∘ o o) b*) 1 2))
  (check-equal? ((∘ o (∘ o b*)) 1 2 3)	((∘ (∘ o o) b*) 1 2 3))
  (check-equal? ((∘ o (∘ o v)) 1)	((∘ (∘ o o) v) 1))
  (check-equal? ((∘ o (∘ o v)) 1 2)	((∘ (∘ o o) v) 1 2))
  (check-equal? ((∘ o (∘ o v*)) 1)	((∘ (∘ o o) v*) 1))
  (check-equal? ((∘ o (∘ o v*)) 1 2)	((∘ (∘ o o) v*) 1 2))
  (check-equal? ((∘ o (∘ o o)) 1)	((∘ (∘ o o) o) 1))
  (check-equal? ((∘ o (∘ o o)) 1 2)	((∘ (∘ o o) o) 1 2))
))
(provide associativity)
